import {
  Race,
  Government,
  PlayerProfile,
  PlayerResources,
  Technology,
  WeaponType,
  PlayerWeapon,
  TargetRealm,
  MothershipModule,
  PlanetColony,
  MarketOrder,
  MercenaryContract,
  RankingEntry,
  Alliance,
  GameMessage,
} from './types';
import { CONVERT_NPC_RACES_TO_TARGET_REALMS } from './stargateNpcRacesData';

export const RACES: Race[] = [
  {
    id: 'tauri',
    name: "Kingdom of Valewyn",
    bonusLabel: "Vanguard bonus (+25%)",
    bonusPercent: 25,
    bankName: "The Royal Treasury",
    attackModifier: 1.25,
    defenseModifier: 1.0,
    incomeModifier: 1.0,
    covertModifier: 1.0,
    description: "The free folk of Valewyn: hardy humans, master castle-builders, and tireless defenders of the Marches.",
  },
  {
    id: 'asgard',
    name: "Sylvan Court",
    bonusLabel: "Wardcraft bonus (+25%)",
    bonusPercent: 25,
    bankName: "Moonwell Reserve",
    attackModifier: 1.0,
    defenseModifier: 1.25,
    incomeModifier: 1.0,
    covertModifier: 1.0,
    description: "Elder elves of the silverwood, keepers of ancient groves, longbow craft, and moonlit wards.",
  },
  {
    id: 'goauld',
    name: "Ashen Dominion",
    bonusLabel: "Tribute bonus (+25%)",
    bonusPercent: 25,
    bankName: "The Ember Hoard",
    attackModifier: 1.0,
    defenseModifier: 1.0,
    incomeModifier: 1.25,
    covertModifier: 1.0,
    description: "Orc clans united beneath a stern war-crown, famed for forgeworks, raiding parties, and iron discipline.",
  },
  {
    id: 'replicator',
    name: "Ironroot Clans",
    bonusLabel: "Crafting bonus (+25%)",
    bonusPercent: 25,
    bankName: "Deepdelve Vault",
    attackModifier: 1.0,
    defenseModifier: 1.0,
    incomeModifier: 1.0,
    covertModifier: 1.25,
    description: "Stout dwarven holds beneath the mountains, whose master-smiths turn ore and runes into unyielding arms.",
  },
  {
    id: 'tollan',
    name: "Dragonborn Covenant",
    bonusLabel: "Lore mastery (+20%)",
    bonusPercent: 20,
    bankName: "The Starfall Reliquary",
    attackModifier: 1.1,
    defenseModifier: 1.1,
    incomeModifier: 1.1,
    covertModifier: 1.1,
    description: "Dragon-blooded sages and knights bound by ancient oaths, skilled in draconic lore and fortress wards.",
  },
];

export const GOVERNMENTS: Government[] = [
  {
    id: 'democracy',
    name: "Free Cities Compact",
    tagline: "Elected reeves and guild councils unite the chartered towns.",
    description: "A league of free cities devoted to open markets, civic duty, diplomacy, and the steady growth of their people.",
    icon: '🏛️',
    ideology: "Civic liberty, fair trade, and common cause",
    economyModifier: 1.30,
    researchModifier: 1.10,
    militaryModifier: 0.85,
    defenseModifier: 1.05,
    colonyModifier: 1.25,
    fleetModifier: 0.90,
    metalMineModifier: 1.15,
    crystalMineModifier: 1.20,
    deutMineModifier: 1.10,
    reputationModifier: 1.30,
    gloryModifier: 1.05,
    subspaceSpeedModifier: 1.05,
    specialPerk: "Chartered Roads: +2 holding slots, steadier public morale, and greater market income.",
    uniqueShipClass: "Silverroad Caravan Guard",
    colorTheme: 'blue',
    strengths: ["+30% Trade & Treasury Income", "+25% Holding Capacity & Growth", "+30% Diplomatic Standing"],
    weaknesses: ["-15% Warband Assault Power", "-10% Muster Speed"],
    edicts: [
      {
        id: 'fed_trade_bill',
        name: "Charter of the Amber Road",
        description: "Lower tolls and escort caravans to bring more goods safely to market.",
        effect: "+20% Market Profits & Treasury Interest",
        cost: "15,000 Crowns",
        durationHours: 24,
      },
      {
        id: 'fed_research_grant',
        name: "Open Scriptorium Grant",
        description: "Fund public scribes, apprentices, and the copying of rare spellbooks.",
        effect: "+15% Lore Study Speed",
        cost: "25,000 Iron, 10,000 Moonstone",
        durationHours: 24,
      },
      {
        id: 'fed_defense_pact',
        name: "Common Shield Oath",
        description: "Rally citizens and sworn guards to reinforce every city wall.",
        effect: "+20% Keep Ward Strength",
        cost: "20,000 Aether",
        durationHours: 24,
      },
    ],
  },
  {
    id: 'junta',
    name: "Iron Crown War Council",
    tagline: "The marshal-lords place every holding at the service of the realm.",
    description: "A martial council that prizes drilled companies, swift musters, stout garrisons, and decisive campaigns.",
    icon: '⚔️',
    ideology: "Honor, discipline, and the shieldwall",
    economyModifier: 0.85,
    researchModifier: 1.00,
    militaryModifier: 1.35,
    defenseModifier: 1.20,
    colonyModifier: 0.90,
    fleetModifier: 1.30,
    metalMineModifier: 1.10,
    crystalMineModifier: 0.95,
    deutMineModifier: 1.25,
    reputationModifier: 0.80,
    gloryModifier: 1.35,
    subspaceSpeedModifier: 1.15,
    specialPerk: "Call to Arms: elite champions muster faster and all warbands gain a combat edge.",
    uniqueShipClass: "Blacksteel Crown Guard",
    colorTheme: 'red',
    strengths: ["+35% Assault Power", "+30% Arms Hall Muster Speed", "+35% Renown from Victories"],
    weaknesses: ["-15% Civilian Income", "-10% Treaty Influence"],
    edicts: [
      {
        id: 'junta_mobilization',
        name: "Marshal’s Muster",
        description: "Call the smiths and quartermasters to ready the realm’s warbands.",
        effect: "+25% Arms Hall Muster Rate",
        cost: "30,000 Iron, 10,000 Aether",
        durationHours: 24,
      },
      {
        id: 'junta_drills',
        name: "Red Banner Exercises",
        description: "Drill the shieldwall and sharpen every champion’s battle craft.",
        effect: "+15% Warband Damage & Critical Chance",
        cost: "25,000 Aether",
        durationHours: 24,
      },
      {
        id: 'junta_garrison',
        name: "Marcher Garrison Decree",
        description: "Send veteran wardens to reinforce vulnerable keeps and passes.",
        effect: "+30% Defense against Invasions",
        cost: "35,000 Iron, 15,000 Crowns",
        durationHours: 24,
      },
    ],
  },
  {
    id: 'technocracy',
    name: "Arcane Conclave",
    tagline: "Archmages and lorekeepers guide the realm through study and spellcraft.",
    description: "A council of scholars devoted to runes, alchemy, healing arts, and the careful study of elder magic.",
    icon: '🧪',
    ideology: "Wisdom, experiment, and arcane stewardship",
    economyModifier: 1.05,
    researchModifier: 1.40,
    militaryModifier: 1.00,
    defenseModifier: 1.15,
    colonyModifier: 1.05,
    fleetModifier: 1.15,
    metalMineModifier: 1.00,
    crystalMineModifier: 1.30,
    deutMineModifier: 1.35,
    reputationModifier: 1.10,
    gloryModifier: 1.10,
    subspaceSpeedModifier: 1.25,
    specialPerk: "Living Grimoire: research advances faster and scouts gain a sharper eye for hidden paths.",
    uniqueShipClass: "Starfall Spellguard",
    colorTheme: 'teal',
    strengths: ["+40% Lore & Research", "+35% Aether Yield", "+25% Leyroad Travel"],
    weaknesses: ["Ordinary Militia Morale", "High Aether Upkeep"],
    edicts: [
      {
        id: 'tech_overclock',
        name: "Grand Enchantment",
        description: "Set the conclave to work through the night on a chosen study.",
        effect: "+25% Lore Study Speed",
        cost: "20,000 Moonstone, 20,000 Aether",
        durationHours: 24,
      },
      {
        id: 'tech_probe_stealth',
        name: "Veilwalker’s Lesson",
        description: "Teach scouts the old paths that hide them from watchtowers.",
        effect: "+35% Scout Infiltration",
        cost: "15,000 Aether",
        durationHours: 24,
      },
      {
        id: 'tech_nanite_boost',
        name: "Golemwright’s Pattern",
        description: "Send rune-bound construct crews to speed the raising of new works.",
        effect: "-20% Building Time",
        cost: "30,000 Moonstone, 15,000 Crowns",
        durationHours: 24,
      },
    ],
  },
  {
    id: 'empire',
    name: "The High Kingdom",
    tagline: "One sovereign crown binds the noble houses and border keeps.",
    description: "A hereditary kingdom that gathers tribute from its vassal holds to strengthen the crown and its sworn champions.",
    icon: '👑',
    ideology: "Fealty, stewardship, and the sovereign crown",
    economyModifier: 1.20,
    researchModifier: 0.90,
    militaryModifier: 1.20,
    defenseModifier: 1.15,
    colonyModifier: 1.15,
    fleetModifier: 1.10,
    metalMineModifier: 1.30,
    crystalMineModifier: 1.15,
    deutMineModifier: 1.05,
    reputationModifier: 0.90,
    gloryModifier: 1.25,
    subspaceSpeedModifier: 1.05,
    specialPerk: "Vassal Oaths: outlying holdings pay greater tribute and royal champions gain stronger armor.",
    uniqueShipClass: "The King’s Griffon Guard",
    colorTheme: 'amber',
    strengths: ["+30% Iron Harvest", "+20% Champion Armor", "+25% Spoils from Victories"],
    weaknesses: ["-10% Lore Growth", "Vassal Holdings Need Careful Stewardship"],
    edicts: [
      {
        id: 'emp_tithe',
        name: "Royal Harvest Due",
        description: "Summon the reeves to deliver their lawful stores to the crown.",
        effect: "+20% Iron and Moonstone Harvest",
        cost: "10,000 Crowns",
        durationHours: 24,
      },
      {
        id: 'emp_grand_fleet',
        name: "Oath of the Crown Guard",
        description: "Equip royal champions with the finest plate from the royal forges.",
        effect: "+20% Champion Armor and Vitality",
        cost: "40,000 Iron, 15,000 Aether",
        durationHours: 24,
      },
      {
        id: 'emp_coronation',
        name: "Coronation of the Realm",
        description: "Hold feasts and tourneys to renew the realm’s loyalty and honor.",
        effect: "+25% Renown and Honor",
        cost: "25,000 Crowns",
        durationHours: 24,
      },
    ],
  },
  {
    id: 'guild',
    name: "Amber Road Merchant Houses",
    tagline: "Caravan masters and moneylenders turn safe roads into prosperity.",
    description: "A mercantile league of caravan houses, market halls, and private guards that rewards trade above conquest.",
    icon: '💎',
    ideology: "Enterprise, contracts, and the open road",
    economyModifier: 1.45,
    researchModifier: 1.05,
    militaryModifier: 0.85,
    defenseModifier: 0.90,
    colonyModifier: 1.20,
    fleetModifier: 1.20,
    metalMineModifier: 1.20,
    crystalMineModifier: 1.25,
    deutMineModifier: 1.15,
    reputationModifier: 1.20,
    gloryModifier: 1.00,
    subspaceSpeedModifier: 1.20,
    specialPerk: "Golden Caravans: wagons carry more goods, the treasury earns extra interest, and shop prices improve.",
    uniqueShipClass: "Amberroad Merchant Train",
    colorTheme: 'emerald',
    strengths: ["+45% Trade & Treasury Wealth", "+50% Caravan Capacity", "+35% Treasury Interest"],
    weaknesses: ["-15% Standing Militia Resolve", "-10% Keep Fortifications"],
    edicts: [
      {
        id: 'guild_monopoly',
        name: "Golden Market Charter",
        description: "Secure exclusive market rights along the neighboring trade roads.",
        effect: "+30% Treasury Daily Interest",
        cost: "30,000 Crowns",
        durationHours: 24,
      },
      {
        id: 'guild_privateer',
        name: "Free-Caravan Writ",
        description: "Hire outriders to recover goods from unsafe roads and bandit trails.",
        effect: "+25% Caravan Spoils Capacity",
        cost: "20,000 Crowns, 10,000 Aether",
        durationHours: 24,
      },
      {
        id: 'guild_subsidies',
        name: "Master Smiths’ Stipend",
        description: "Grant guild contracts to reduce the cost of arms and armor.",
        effect: "-15% Arms and Armor Costs",
        cost: "25,000 Crowns",
        durationHours: 24,
      },
    ],
  },
  {
    id: 'theocracy',
    name: "Radiant Synod",
    tagline: "The faithful gather beneath the sun-banner and the vows of the temples.",
    description: "A sacred dominion led by abbots and oathbound champions, where shrines strengthen defenses and inspire the people.",
    icon: '☀️',
    ideology: "Faith, mercy, and the holy oath",
    economyModifier: 1.10,
    researchModifier: 0.80,
    militaryModifier: 1.25,
    defenseModifier: 1.35,
    colonyModifier: 1.10,
    fleetModifier: 1.10,
    metalMineModifier: 1.05,
    crystalMineModifier: 1.10,
    deutMineModifier: 1.25,
    reputationModifier: 0.85,
    gloryModifier: 1.60,
    subspaceSpeedModifier: 1.10,
    specialPerk: "Consecrated Wards: keeps gain stronger protection and deeds of valor earn lasting renown.",
    uniqueShipClass: "Sunspire Templar Order",
    colorTheme: 'yellow',
    strengths: ["+35% Keep Ward Strength", "+60% Renown from Deeds", "+25% Crusader Assault Power"],
    weaknesses: ["-20% Secular Scholarship", "Rigid doctrine complicates diplomacy"],
    edicts: [
      {
        id: 'theo_crusade',
        name: "Sunlit Crusade",
        description: "Bless the banners and send the temple knights against a rival realm.",
        effect: "+25% Warband Damage against Hostile Realms",
        cost: "20,000 Crowns, 15,000 Aether",
        durationHours: 24,
      },
      {
        id: 'theo_iris_ward',
        name: "Blessing of the Dawnward",
        description: "Consecrate the keeps with protective runes and healing incense.",
        effect: "+30% Ward Renewal",
        cost: "25,000 Moonstone, 15,000 Aether",
        durationHours: 24,
      },
      {
        id: 'theo_pilgrimage',
        name: "Pilgrimage of the Seven Shrines",
        description: "Welcome pilgrims whose offerings strengthen the temples and the crown.",
        effect: "+50% Renown for 24 Hours",
        cost: "25,000 Crowns",
        durationHours: 24,
      },
    ],
  },
  {
    id: 'hive',
    name: "Mycelium Court",
    tagline: "A living woodland compact woven from root, spore, and shared memory.",
    description: "A nature-bound collective whose druids, sprites, and woodland folk coordinate harvests with uncanny harmony.",
    icon: '🤖',
    ideology: "Communion with the living land",
    economyModifier: 1.25,
    researchModifier: 1.20,
    militaryModifier: 1.15,
    defenseModifier: 1.10,
    colonyModifier: 1.30,
    fleetModifier: 1.15,
    metalMineModifier: 1.25,
    crystalMineModifier: 1.20,
    deutMineModifier: 1.20,
    reputationModifier: 0.60,
    gloryModifier: 0.90,
    subspaceSpeedModifier: 1.15,
    specialPerk: "Rootbound Communion: unrest is rare, and woodland manors yield abundant food and timber.",
    uniqueShipClass: "Briarheart Groveguard",
    colorTheme: 'purple',
    strengths: ["+30% Mana from Sacred Groves", "+30% Settlement Growth", "+25% Automated Harvest"],
    weaknesses: ["-40% Standing with distant courts", "Traditional markets are less welcoming"],
    edicts: [
      {
        id: 'hive_overclock',
        name: "Rootsong Harvest",
        description: "Guide the grove stewards to gather a greater harvest from the land.",
        effect: "+25% Resource Harvest Speed",
        cost: "20,000 Aether",
        durationHours: 24,
      },
      {
        id: 'hive_swarm_link',
        name: "Whispering Rootbond",
        description: "Bind the wardens together with a shared woodland rite.",
        effect: "+20% Warband Evasion & Ward Renewal",
        cost: "20,000 Moonstone, 10,000 Crowns",
        durationHours: 24,
      },
      {
        id: 'hive_debris_sweep',
        name: "Scavenger Sprite Revel",
        description: "Send clever sprites to reclaim useful goods from a battlefield.",
        effect: "+30% Battlefield Recovery Yield",
        cost: "15,000 Iron, 10,000 Aether",
        durationHours: 24,
      },
    ],
  },
  {
    id: 'anarchy',
    name: "Free March Clans",
    tagline: "Independent valleys and hill clans defend their ancient freedoms together.",
    description: "A loose confederation of frontier clans skilled in ambush, sabotage, mutual defense, and resistance to tyrants.",
    icon: '🏴',
    ideology: "Local custom, mutual aid, and fierce independence",
    economyModifier: 1.10,
    researchModifier: 1.10,
    militaryModifier: 1.10,
    defenseModifier: 1.25,
    colonyModifier: 1.20,
    fleetModifier: 1.25,
    metalMineModifier: 1.10,
    crystalMineModifier: 1.10,
    deutMineModifier: 1.10,
    reputationModifier: 0.95,
    gloryModifier: 1.15,
    subspaceSpeedModifier: 1.30,
    specialPerk: "Marcher’s Pact: scouts move swiftly, plots are harder to uncover, and upkeep is reduced.",
    uniqueShipClass: "Greencloak Border Riders",
    colorTheme: 'zinc',
    strengths: ["-40% Warband Upkeep", "+35% Ambush & Infiltration Success", "+30% March Speed"],
    weaknesses: ["-15% Heavy Champion Armor", "No central crown to collect great tribute"],
    edicts: [
      {
        id: 'anarchy_partisan_cells',
        name: "Passwatch Bands",
        description: "Arm local militias with bows and hardened barricades.",
        effect: "+35% Defense against Siege Assaults",
        cost: "20,000 Iron, 5,000 Crowns",
        durationHours: 24,
      },
      {
        id: 'anarchy_sabotage',
        name: "Nightpath Uprising",
        description: "Send covert partisans to disrupt an enemy’s supply stores.",
        effect: "+30% Sabotage Success",
        cost: "15,000 Crowns",
        durationHours: 24,
      },
      {
        id: 'anarchy_open_source',
        name: "Common Scriptorium",
        description: "Share maps and spellbooks freely among every marcher village.",
        effect: "+15% Research Speed & Free Lore Unlocks",
        cost: "15,000 Moonstone",
        durationHours: 24,
      },
    ],
  },
  {
    id: 'aristocracy',
    name: "Noble Houses of Dawn",
    tagline: "Ancient bloodlines gather in a high court of banners and alliances.",
    description: "A courtly alliance of noble houses whose wealth, heralds, and storied champions shape the balance of power.",
    icon: '⚜️',
    ideology: "Heritage, patronage, and courtly honor",
    economyModifier: 1.15,
    researchModifier: 1.15,
    militaryModifier: 1.20,
    defenseModifier: 1.10,
    colonyModifier: 1.05,
    fleetModifier: 1.25,
    metalMineModifier: 1.10,
    crystalMineModifier: 1.20,
    deutMineModifier: 1.15,
    reputationModifier: 1.40,
    gloryModifier: 1.40,
    subspaceSpeedModifier: 1.10,
    specialPerk: "Heraldic Favor: sworn officers strengthen their retinues and victories bring prestige to every house.",
    uniqueShipClass: "Dawncourt Lionguard",
    colorTheme: 'indigo',
    strengths: ["+25% Champion Officer Auras", "+40% Diplomatic Renown", "+15% Critical Strike Chance"],
    weaknesses: ["-15% Commoner Harvest Yield", "High courtly upkeep"],
    edicts: [
      {
        id: 'arist_officer_commission',
        name: "Noble Retainer Commission",
        description: "Appoint a worthy scion to lead and inspire the household guard.",
        effect: "+25% Champion XP and Aura Strength",
        cost: "25,000 Crowns",
        durationHours: 24,
      },
      {
        id: 'arist_diplomatic_envoy',
        name: "Dawncourt Embassy",
        description: "Send heralds bearing gifts to neighboring courts and free cities.",
        effect: "+35% Renown and Foreign Favor",
        cost: "20,000 Crowns, 10,000 Moonstone",
        durationHours: 24,
      },
      {
        id: 'arist_noble_treasury',
        name: "Household Reliquary",
        description: "Open the ancestral vault to reward the house’s victorious champions.",
        effect: "+30% Renown from Combat Victories",
        cost: "30,000 Iron, 15,000 Crowns",
        durationHours: 24,
      },
    ],
  },
];

export const INITIAL_PROFILE: PlayerProfile = {
  id: 'usr-1',
  username: 'demo',
  displayName: 'Warden Aria Vale',
  race: 'tauri',
  governmentId: 'junta',
  rankName: 'Realm Warden',
  rankLevel: 3,
  glory: 1250,
  reputation: 680,
  defconLevel: 0,
  vacationUntil: null,
  ascended: false,
  lastTurnAt: new Date().toISOString(),
};

export const INITIAL_RESOURCES: PlayerResources = {
  credits: 500000,
  naquadah: 125000,
  bankedNaquadah: 500000,
  attackTurns: 48,
  untrainedUnits: 1600,
  miners: 650,
  lifers: 150,
  unitProduction: 12,
  attackUnits: 850,
  defenseUnits: 1200,
  spies: 160,
  antiSpies: 140,
  superUnits: 25,
  metal: 85000,
  crystal: 54000,
  deuterium: 28000,
  oreStockpile: {
    copper_ore: 3,
    tin_ore: 2,
    iron_ore: 2,
    silver_ore: 2,
    gold_ore: 0,
    moonstone_ore: 0,
    nightglass_ore: 0,
    sunsteel_ore: 0,
    oathiron_ore: 0,
  },
  food: 42000,
  maxFood: 250000,
  water: 58000,
  maxWater: 300000,
  totalPopulation: 14000000,
  energy: 450,
  maxEnergy: 600,
  gateTokens: 25,
  dimensionalTokens: 12,
  raidTokens: 6,
};

export const INITIAL_TECHNOLOGIES: Technology[] = [
  {
    id: 'tech-1',
    key: 'tech_offense_plasma',
    name: 'Runecraft of Battle',
    category: 'offense',
    baseCost: 25000,
    costGrowth: 1.35,
    level: 2,
    description: 'The martial runes that lend every blade, bow, and siege engine greater force.',
  },
  {
    id: 'tech-2',
    key: 'tech_offense_tachyon',
    name: 'Dragonfire Mastery',
    category: 'offense',
    baseCost: 65000,
    costGrowth: 1.45,
    level: 1,
    description: 'Study the ancient breath-runes said to pierce even a dragon’s strongest scales.',
  },
  {
    id: 'tech-3',
    key: 'tech_defense_shield',
    name: 'Wardcraft of the Sylvan Court',
    category: 'defense',
    baseCost: 30000,
    costGrowth: 1.35,
    level: 3,
    description: 'Layered protective wards that blunt arrows, blades, and siege blows.',
  },
  {
    id: 'tech-4',
    key: 'tech_defense_armor',
    name: 'Masterwork Plate Forging',
    category: 'defense',
    baseCost: 45000,
    costGrowth: 1.4,
    level: 2,
    description: 'Forge layered steel and moon-silver plate to protect keeps and champion retinues.',
  },
  {
    id: 'tech-5',
    key: 'tech_covert_cloak',
    name: 'Veilwalking Lore',
    category: 'covert',
    baseCost: 20000,
    costGrowth: 1.3,
    level: 2,
    description: 'Teach scouts to move unseen through shadowed passages and guarded halls.',
  },
  {
    id: 'tech-6',
    key: 'tech_anti_sensors',
    name: 'Farseer’s Watch',
    category: 'anti-covert',
    baseCost: 22000,
    costGrowth: 1.32,
    level: 2,
    description: 'Train vigilant watchers to detect spies, hidden trails, and approaching warbands.',
  },
];

export const WEAPON_TYPES: WeaponType[] = [
  // ==================== 1. WEAPONS (SMALL ARMS) ====================
  {
    id: 'wpn-m4a1',
    name: "Ranger’s Longbow",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 1,
    power: 28,
    attack: 28,
    defense: 8,
    price: 650,
    crewReq: 1,
    upkeep: 5,
    mass: "Light kit",
    range: "Longbow reach",
    specSummary: "First-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Ranger’s Longbow is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-scarh',
    name: "Dwarven Repeater Crossbow",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 2,
    power: 52,
    attack: 52,
    defense: 14,
    price: 1450,
    crewReq: 1,
    upkeep: 10,
    mass: "Light kit",
    range: "Longbow reach",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Dwarven Repeater Crossbow is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-p90',
    name: "Moonsteel Shortsword",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 1,
    power: 34,
    attack: 34,
    defense: 12,
    price: 850,
    crewReq: 1,
    upkeep: 6,
    mass: "Light kit",
    range: "Close-quarters reach",
    specSummary: "First-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Moonsteel Shortsword is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-barrett',
    name: "Giantbane Greatbow",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 2,
    power: 95,
    attack: 95,
    defense: 25,
    price: 3200,
    crewReq: 2,
    upkeep: 25,
    mass: "Light kit",
    range: "Longbow reach",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Giantbane Greatbow is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-benelli',
    name: "Breaching Warhammer",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 1,
    power: 32,
    attack: 32,
    defense: 16,
    price: 720,
    crewReq: 1,
    upkeep: 5,
    mass: "Light kit",
    range: "Close-quarters reach",
    specSummary: "First-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Breaching Warhammer is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },

  // ==================== 1. WEAPONS (CREW-SERVED & HEAVY) ====================
  {
    id: 'wpn-m240b',
    name: "Stormcaller’s Repeating Crossbow",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 2,
    power: 75,
    attack: 75,
    defense: 35,
    price: 2400,
    crewReq: 2,
    upkeep: 18,
    mass: "Light kit",
    range: "Longbow reach",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Stormcaller’s Repeating Crossbow is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-m2hb',
    name: "Ogrebreaker Ballista",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 2,
    power: 110,
    attack: 110,
    defense: 50,
    price: 3800,
    crewReq: 3,
    upkeep: 30,
    mass: "Light kit",
    range: "Castle-wall range",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Ogrebreaker Ballista is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-mk19',
    name: "Alchemist’s Fire Mortar",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 2,
    power: 135,
    attack: 135,
    defense: 45,
    price: 4600,
    crewReq: 3,
    upkeep: 35,
    mass: "Light kit",
    range: "Castle-wall range",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Alchemist’s Fire Mortar is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-tow',
    name: "Dragonpiercer Heavy Arbalest",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 3,
    power: 220,
    attack: 220,
    defense: 40,
    price: 7800,
    crewReq: 2,
    upkeep: 60,
    mass: "Battle-ready",
    range: "Longbow reach",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Dragonpiercer Heavy Arbalest is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-stinger',
    name: "Wyvernhook Bolts",
    category: 'Defense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 2,
    power: 140,
    attack: 140,
    defense: 85,
    price: 4900,
    crewReq: 2,
    upkeep: 40,
    mass: "Light kit",
    range: "Longbow reach",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Wyvernhook Bolts is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },

  // ==================== 1. WEAPONS (ARTILLERY & ROCKETS) ====================
  {
    id: 'wpn-m777',
    name: "Trebuchet of the High March",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 3,
    power: 260,
    attack: 260,
    defense: 60,
    price: 9200,
    crewReq: 5,
    upkeep: 80,
    mass: "Battle-ready",
    range: "Castle-wall range",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Trebuchet of the High March is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-paladin',
    name: "Stonebreaker Siege Engine",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 3,
    power: 340,
    attack: 340,
    defense: 120,
    price: 14500,
    crewReq: 4,
    upkeep: 120,
    mass: "Battle-ready",
    range: "Castle-wall range",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Stonebreaker Siege Engine is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-himars',
    name: "Stormfall Rocket Cart",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 4,
    power: 520,
    attack: 520,
    defense: 90,
    price: 23000,
    crewReq: 3,
    upkeep: 180,
    mass: "Battle-ready",
    range: "Castle-wall range",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Stormfall Rocket Cart is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-heavy-mlrs',
    name: "Cinder Volley Rack",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 4,
    power: 610,
    attack: 610,
    defense: 80,
    price: 27500,
    crewReq: 4,
    upkeep: 220,
    mass: "Battle-ready",
    range: "Close-quarters reach",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Cinder Volley Rack is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },

  // ==================== 1. WEAPONS (AIR DEFENSE & NAVAL) ====================
  {
    id: 'wpn-phalanx',
    name: "Ironbark Thornwall",
    category: 'Defense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 3,
    power: 280,
    attack: 180,
    defense: 280,
    price: 11500,
    crewReq: 2,
    upkeep: 90,
    mass: "Battle-ready",
    range: "Close-quarters reach",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Ironbark Thornwall is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-patriot',
    name: "Skyward Arrow Battery",
    category: 'Defense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 4,
    power: 540,
    attack: 210,
    defense: 540,
    price: 29000,
    crewReq: 4,
    upkeep: 240,
    mass: "Battle-ready",
    range: "Close-quarters reach",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Skyward Arrow Battery is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-mk45',
    name: "Harborkeep Bombard",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 3,
    power: 310,
    attack: 310,
    defense: 140,
    price: 13800,
    crewReq: 3,
    upkeep: 110,
    mass: "Battle-ready",
    range: "Castle-wall range",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Harborkeep Bombard is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-harpoon',
    name: "Leviathan Harpoon Launcher",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 3,
    power: 390,
    attack: 390,
    defense: 60,
    price: 16500,
    crewReq: 2,
    upkeep: 130,
    mass: "Battle-ready",
    range: "Close-quarters reach",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Leviathan Harpoon Launcher is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },

  // ==================== 1. WEAPONS (EXOTIC ENERGY & STARGATE) ====================
  {
    id: 'wpn-1',
    name: "Sunfire Scepter",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 2,
    power: 65,
    attack: 65,
    defense: 20,
    price: 1200,
    crewReq: 1,
    upkeep: 8,
    mass: "Light kit",
    range: "Longbow reach",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Sunfire Scepter is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-2',
    name: "Runic War Staff",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 3,
    power: 160,
    attack: 160,
    defense: 45,
    price: 4500,
    crewReq: 2,
    upkeep: 30,
    mass: "Battle-ready",
    range: "Longbow reach",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Runic War Staff is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-3',
    name: "Gryphon Warden’s Longbow",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 5,
    power: 580,
    attack: 580,
    defense: 120,
    price: 19500,
    crewReq: 1,
    upkeep: 150,
    mass: "Masterwork heavy",
    range: "Longbow reach",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Gryphon Warden’s Longbow is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-asgard-beam',
    name: "Frostwyrm Breath Lances",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 5,
    power: 850,
    attack: 850,
    defense: 220,
    price: 38000,
    crewReq: 3,
    upkeep: 280,
    mass: "Masterwork heavy",
    range: "Longbow reach",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Frostwyrm Breath Lances is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-ori-beam',
    name: "Celestial Judgment Cannon",
    category: 'Offense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 5,
    power: 1150,
    attack: 1150,
    defense: 300,
    price: 65000,
    crewReq: 0,
    upkeep: 420,
    mass: "Masterwork heavy",
    range: "Longbow reach",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Celestial Judgment Cannon is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },

  // ==================== 2. ARMORS (INFANTRY BODY ARMOR) ====================
  {
    id: 'arm-kevlar',
    name: "Ranger’s Leather Jerkin & Coif",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 1,
    power: 35,
    attack: 0,
    defense: 35,
    price: 750,
    crewReq: 1,
    upkeep: 4,
    mass: "Light kit",
    specSummary: "First-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Ranger’s Leather Jerkin & Coif is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-ceramic-plate',
    name: "Tempered Steel Brigandine",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 2,
    power: 85,
    attack: 0,
    defense: 85,
    price: 2100,
    crewReq: 1,
    upkeep: 10,
    mass: "Light kit",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Tempered Steel Brigandine is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-eod-juggernaut',
    name: "Stonewall Juggernaut Plate",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 3,
    power: 180,
    attack: 15,
    defense: 180,
    price: 6200,
    crewReq: 1,
    upkeep: 25,
    mass: "Battle-ready",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Stonewall Juggernaut Plate is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-exoskeleton',
    name: "Runebound Titan Harness",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 4,
    power: 340,
    attack: 45,
    defense: 340,
    price: 14500,
    crewReq: 1,
    upkeep: 65,
    mass: "Battle-ready",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Runebound Titan Harness is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-trinium-nano',
    name: "Moonsteel Scaleweave",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 5,
    power: 620,
    attack: 75,
    defense: 620,
    price: 32000,
    crewReq: 1,
    upkeep: 120,
    mass: "Masterwork heavy",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Moonsteel Scaleweave is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },

  // ==================== 2. ARMORS (COMBAT VEHICLES & TANKS) ====================
  {
    id: 'arm-hmmwv',
    name: "Ranger’s Warhorse Barding",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 1,
    power: 55,
    attack: 20,
    defense: 55,
    price: 1800,
    crewReq: 4,
    upkeep: 15,
    mass: "Light kit",
    specSummary: "First-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Ranger’s Warhorse Barding is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-stryker',
    name: "Ironhide War Wagon",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 2,
    power: 145,
    attack: 45,
    defense: 145,
    price: 5400,
    crewReq: 2,
    upkeep: 35,
    mass: "Light kit",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Ironhide War Wagon is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-jltv',
    name: "Bastion Siege Carriage",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 2,
    power: 175,
    attack: 35,
    defense: 175,
    price: 6800,
    crewReq: 4,
    upkeep: 40,
    mass: "Light kit",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Bastion Siege Carriage is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-bradley',
    name: "Gryphon-Rider Battle Chariot",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 3,
    power: 280,
    attack: 115,
    defense: 280,
    price: 11800,
    crewReq: 3,
    upkeep: 75,
    mass: "Battle-ready",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Gryphon-Rider Battle Chariot is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-abrams',
    name: "Dreadnought Ram-Beast Barding",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 4,
    power: 590,
    attack: 280,
    defense: 590,
    price: 27000,
    crewReq: 4,
    upkeep: 160,
    mass: "Battle-ready",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Dreadnought Ram-Beast Barding is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-leopard2',
    name: "Dragonbone Siege Barding",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 4,
    power: 620,
    attack: 270,
    defense: 620,
    price: 28500,
    crewReq: 4,
    upkeep: 170,
    mass: "Battle-ready",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Dragonbone Siege Barding is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },

  // ==================== 2. ARMORS (HARDENED HULL PLATING & SUPPORT) ====================
  {
    id: 'arm-m88a2',
    name: "Fieldwright’s Recovery Wagon",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 2,
    power: 125,
    attack: 10,
    defense: 125,
    price: 4200,
    crewReq: 3,
    upkeep: 25,
    mass: "Light kit",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Fieldwright’s Recovery Wagon is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-era-kits',
    name: "Runic Reactive Plate",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 2,
    power: 110,
    attack: 0,
    defense: 110,
    price: 3600,
    crewReq: 0,
    upkeep: 15,
    mass: "Light kit",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Runic Reactive Plate is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },
  {
    id: 'arm-sloped-trinium',
    name: "King’s Aegis Plate",
    category: 'Defense',
    itemType: 'armor',
    subCategory: "Mail, Plate & War Barding",
    tier: 5,
    power: 780,
    attack: 50,
    defense: 780,
    price: 42000,
    crewReq: 0,
    upkeep: 190,
    mass: "Masterwork heavy",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "King’s Aegis Plate is fashioned by the royal armorers from layered leather, mail, plate, and warding runes for the front line.",
    maxDurability: 100,
  },

  // ==================== 3. SHIELDS (PERSONAL FORCE FIELDS & DEFLECTORS) ====================
  {
    id: 'shd-riot-ballistic',
    name: "Oak-and-Iron Buckler",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 1,
    power: 30,
    attack: 0,
    defense: 30,
    price: 650,
    crewReq: 1,
    upkeep: 2,
    mass: "Light kit",
    specSummary: "First-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Oak-and-Iron Buckler is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'shd-carbon-barrier',
    name: "Tower Shield of the Stonewall",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 2,
    power: 75,
    attack: 0,
    defense: 75,
    price: 1950,
    crewReq: 1,
    upkeep: 8,
    mass: "Light kit",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Tower Shield of the Stonewall is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'shd-portable-emp',
    name: "Rune-Warded Pavise",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 3,
    power: 160,
    attack: 0,
    defense: 160,
    price: 5400,
    crewReq: 1,
    upkeep: 20,
    mass: "Battle-ready",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Rune-Warded Pavise is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'shd-ribbon',
    name: "Serpent Queen’s Ward Bracer",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 3,
    power: 230,
    attack: 20,
    defense: 230,
    price: 8200,
    crewReq: 1,
    upkeep: 35,
    mass: "Battle-ready",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Serpent Queen’s Ward Bracer is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'shd-ancient-personal',
    name: "Amulet of the Veiled Saint",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 4,
    power: 420,
    attack: 0,
    defense: 420,
    price: 18000,
    crewReq: 1,
    upkeep: 60,
    mass: "Battle-ready",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Amulet of the Veiled Saint is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },

  // ==================== 3. SHIELDS (TACTICAL & VEHICLE DEFLECTORS) ====================
  {
    id: 'shd-trophy-aps',
    name: "Guardian’s Counterward",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 3,
    power: 210,
    attack: 30,
    defense: 210,
    price: 7600,
    crewReq: 0,
    upkeep: 35,
    mass: "Battle-ready",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Guardian’s Counterward is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'shd-reactive-particle',
    name: "Stormglass Ward Screen",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 4,
    power: 380,
    attack: 0,
    defense: 380,
    price: 15500,
    crewReq: 2,
    upkeep: 70,
    mass: "Battle-ready",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Stormglass Ward Screen is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'shd-subspace-disruption',
    name: "Mageshield of the Fold",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 4,
    power: 540,
    attack: 40,
    defense: 540,
    price: 24000,
    crewReq: 2,
    upkeep: 110,
    mass: "Battle-ready",
    specSummary: "Fourth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Mageshield of the Fold is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },

  // ==================== 3. SHIELDS (PLANETARY & ORBITAL AEGIS) ====================
  {
    id: 'wpn-4',
    name: "Rampart Watch Ballistae",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 2,
    power: 75,
    attack: 25,
    defense: 75,
    price: 1400,
    crewReq: 1,
    upkeep: 15,
    mass: "Light kit",
    specSummary: "Second-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Rampart Watch Ballistae is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'wpn-5',
    name: "Runic Ballista Battery",
    category: 'Defense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 3,
    power: 180,
    attack: 80,
    defense: 180,
    price: 5200,
    crewReq: 3,
    upkeep: 45,
    mass: "Battle-ready",
    specSummary: "Third-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Runic Ballista Battery is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'wpn-6',
    name: "Sunspire Keep Ballista",
    category: 'Defense',
    itemType: 'weapon',
    subCategory: "Blades, Bows & Siege Arms",
    tier: 5,
    power: 520,
    attack: 250,
    defense: 520,
    price: 18500,
    crewReq: 2,
    upkeep: 140,
    mass: "Masterwork heavy",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Sunspire Keep Ballista is a trusted arm of the realm’s champions, forged for border skirmishes, castle defense, and dragon hunts.",
    maxDurability: 100,
  },
  {
    id: 'shd-asgard-bubble',
    name: "Aegis Dome of the Frost Court",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 5,
    power: 880,
    attack: 0,
    defense: 880,
    price: 39000,
    crewReq: 0,
    upkeep: 210,
    mass: "Masterwork heavy",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Aegis Dome of the Frost Court is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'shd-atlantis-grid',
    name: "Veil of the Sunken Citadel",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 5,
    power: 1450,
    attack: 0,
    defense: 1450,
    price: 82000,
    crewReq: 0,
    upkeep: 350,
    mass: "Masterwork heavy",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Veil of the Sunken Citadel is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
  {
    id: 'shd-ori-barrier',
    name: "Celestial Oathward",
    category: 'Defense',
    itemType: 'shield',
    subCategory: "Shields & Arcane Wards",
    tier: 5,
    power: 1950,
    attack: 80,
    defense: 1950,
    price: 125000,
    crewReq: 0,
    upkeep: 480,
    mass: "Masterwork heavy",
    specSummary: "Fifth-rank craft of tempered iron, ashwood, leather, and protective runes.",
    doctrine: "Keep the shieldwall; hunt the monsters beyond the Marches.",
    description: "Celestial Oathward is raised by keep wardens and battle-mages; its wood, steel, and protective runes turn aside incoming blows.",
    maxDurability: 100,
  },
];

export const INITIAL_PLAYER_WEAPONS: PlayerWeapon[] = [
  { id: 'pw-1', weaponTypeId: 'wpn-1', quantity: 240, durability: 95 },
  { id: 'pw-2', weaponTypeId: 'wpn-2', quantity: 85, durability: 88 },
  { id: 'pw-3', weaponTypeId: 'wpn-4', quantity: 310, durability: 92 },
  { id: 'pw-4', weaponTypeId: 'wpn-5', quantity: 70, durability: 80 },
  { id: 'pw-5', weaponTypeId: 'wpn-m4a1', quantity: 180, durability: 96 },
  { id: 'pw-6', weaponTypeId: 'arm-kevlar', quantity: 140, durability: 90 },
  { id: 'pw-7', weaponTypeId: 'arm-ceramic-plate', quantity: 55, durability: 94 },
  { id: 'pw-8', weaponTypeId: 'arm-hmmwv', quantity: 18, durability: 85 },
  { id: 'pw-9', weaponTypeId: 'shd-riot-ballistic', quantity: 95, durability: 92 },
  { id: 'pw-10', weaponTypeId: 'shd-portable-emp', quantity: 25, durability: 88 },
];

const BASE_TARGET_REALMS: TargetRealm[] = [
  {
    id: 'tgt-1',
    commanderName: 'High Marshal Darius Blackthorn',
    race: "Ashen Dominion",
    rank: 'High Realm Sovereign',
    score: 94200,
    estimatedUnits: 1450,
    estimatedNaquadah: 280000,
    isProtected: false,
    defenseLevel: 3,
    antiCovertLevel: 2,
  },
  {
    id: 'tgt-2',
    commanderName: 'Matriarch Vexa Ashhand',
    race: "Ashen Dominion",
    rank: 'Emberthane',
    score: 76500,
    estimatedUnits: 980,
    estimatedNaquadah: 195000,
    isProtected: false,
    defenseLevel: 2,
    antiCovertLevel: 3,
  },
  {
    id: 'tgt-3',
    commanderName: 'Ironroot Clans Hive Block 4',
    race: 'Ironroot Clans',
    rank: 'Rune Golem',
    score: 112000,
    estimatedUnits: 2100,
    estimatedNaquadah: 420000,
    isProtected: false,
    defenseLevel: 4,
    antiCovertLevel: 4,
  },
  {
    id: 'tgt-4',
    commanderName: 'Free March Company',
    race: "Valewyn Outlaw",
    rank: 'Road Reaver',
    score: 41000,
    estimatedUnits: 550,
    estimatedNaquadah: 85000,
    isProtected: false,
    defenseLevel: 1,
    antiCovertLevel: 1,
  },
  {
    id: 'tgt-5',
    commanderName: 'Prince Kael Emberwing',
    race: "Ashen Dominion Ascended",
    rank: 'Wyrm Sovereign',
    score: 185000,
    estimatedUnits: 3400,
    estimatedNaquadah: 890000,
    isProtected: true,
    defenseLevel: 5,
    antiCovertLevel: 5,
  },
];

export const TARGET_REALMS: TargetRealm[] = [
  ...BASE_TARGET_REALMS,
  ...CONVERT_NPC_RACES_TO_TARGET_REALMS(),
];

export const INITIAL_MOTHERSHIP_MODULES: MothershipModule[] = [
  { key: 'hull', name: 'Dragonbone-Reinforced Harness', level: 3, baseCost: 40000, benefit: '+1,500 Hull Integrity' },
  { key: 'volley_bays', name: 'Volley Bow Racks', level: 2, baseCost: 35000, benefit: '+250 Strike Volley Power' },
  { key: 'shields', name: 'Moonstone Ward Matrix', level: 3, baseCost: 45000, benefit: '+1,800 Shield Capacity' },
  { key: 'hangars', name: 'Royal Aviary & Griffon Roost', level: 2, baseCost: 30000, benefit: '+12 Interceptor Squadrons' },
  { key: 'scanners', name: 'Farseer Watchtower Array', level: 2, baseCost: 28000, benefit: '+2 Sector Recon Range' },
  { key: 'jump_drive', name: 'Leyroad Drive Engine Core', level: 1, baseCost: 60000, benefit: '-15% Travel Turn Consumption' },
];

export const INITIAL_PLANETS: PlanetColony[] = [
  {
    id: 'pl-homeworld',
    name: "Valewyn Crownlands",
    coordinate: '1:204:8',
    biome: "Greenheart Vale",
    level: 5,
    incomeBonus: 35000,
    defenseBonus: 65000,
    maintenanceCost: 10750,
    moonName: "The Silvermoon",
    jumpGateLevel: 2,
    isHomeworld: true,
    fieldsUsed: 84,
    fieldsMax: 188,
    temperature: '+18°C',
    diameterKm: 12742,
    hasMoon: true,
    metalProductionRate: 48500,
    crystalProductionRate: 29400,
    deuteriumProductionRate: 18200,
    naquadahProductionRate: 35000,
    energyProductionRate: 850,
    specialization: 'homeworld',
    governor: "Queen Elowen Vale",
    taxPolicy: 'balanced',
    foodStockpile: 35000,
    foodCapacity: 100000,
    foodProductionRate: 14200,
    foodConsumptionRate: 8200,
    waterStockpile: 48000,
    waterCapacity: 120000,
    waterProductionRate: 18500,
    waterConsumptionRate: 10000,
    population: {
      total: 14000000,
      growthRatePerHour: 24500,
      housingCapacity: 22000000,
      happiness: 90,
      unrest: 10,
      strata: {
        farmers: 2400000,
        hydrologists: 2400000,
        miners: 2800000,
        industrialWorkers: 2600000,
        scientists: 1400000,
        administrators: 800000,
        militaryRecruits: 1600000,
      },
      livingStandard: 'utopian',
      rationingLevel: 'abundant',
    },
    lifeSupportFacilities: {
      hydroponicsDomes: 12,
      bioFarms: 8,
      geneticCropLabs: 5,
      deepAquiferPumps: 14,
      moistureCondensers: 10,
      desalinationPlants: 9,
      subsurfaceCisterns: 12,
      atmosphereScrubbers: 8,
    },
    hazards: [
      {
        id: 'hzd-earth-1',
        name: 'Dreadmoor Miasma',
        type: 'acid_rain',
        severity: 'low',
        icon: '🌧️',
        effectDescription: 'Atmospheric particulates reduce natural crop yields by 5% and increase water filtration loads.',
        habitabilityPenalty: 5,
        popGrowthPenalty: 4,
        waterContaminationPercent: 6,
        isMitigated: true,
        mitigationProjectName: 'Keep Geo-Scrubber Array',
      },
      {
        id: 'hzd-earth-2',
        name: 'Stormpeak Quake Fault',
        type: 'tectonic_fault',
        severity: 'moderate',
        icon: '🌋',
        effectDescription: 'Seismic tremors cause sporadic power grid disruptions and reduce building stability.',
        habitabilityPenalty: 8,
        popGrowthPenalty: 6,
        waterContaminationPercent: 4,
        isMitigated: false,
        mitigationProjectName: 'Runic Stoneward Brace',
        mitigationCost: { metal: 45000, crystal: 30000, deuterium: 10000, naquadah: 15000 },
      },
    ],
    plunge: {
      plungeIndex: 8,
      stage: 'stable',
      trend: 'stable',
      reasons: ['Abundant food & clean aquifer water surpluses', 'High planetary happiness index'],
      activeCrises: [],
      interventionsAvailable: [
        {
          id: 'int-relief-drop-pl0',
          name: 'Harvest Relief Caravan',
          category: 'logistics',
          description: 'Deploy atmospheric cargo lifters to distribute 5,000 Food and 5,000 Water directly to strained urban sectors.',
          cost: { food: 5000, water: 5000, energy: 50 },
          plungeReduction: 12,
          happinessBonus: 10,
          cooldownMinutes: 15,
        },
        {
          id: 'int-welfare-stimulus-pl0',
          name: 'Royal Bread & Hearth Fund',
          category: 'welfare',
          description: 'Disburse 25,000 Crowns and credits to subsidize healthcare and colonial living standards.',
          cost: { naquadah: 25000, credits: 500 },
          plungeReduction: 15,
          happinessBonus: 14,
          cooldownMinutes: 30,
        },
        {
          id: 'int-peacekeeper-patrol-pl0',
          name: 'Crown Guard and Royal Watch Muster',
          category: 'martial',
          description: 'Deploy elite Jaffa and Tau\'ri security cadres to suppress black markets and quell civil unrest.',
          cost: { naquadah: 10000, metal: 12000 },
          plungeReduction: 18,
          happinessBonus: -4,
          cooldownMinutes: 20,
        },
      ],
    },
    facilities: {
      roboticsFactory: 8,
      shipyard: 10,
      researchLab: 12,
      allianceDepot: 3,
      missileSilo: 6,
      naniteFactory: 4,
      terraformer: 2,
    },
    mines: {
      metalMine: 24,
      crystalMine: 20,
      deuteriumSynthesizer: 18,
      solarPlant: 22,
      fusionReactor: 12,
      naquadahCoreTap: 16,
    },
    defenses: {
      rocketLauncher: 850,
      lightLaser: 420,
      heavyLaser: 180,
      gaussCannon: 65,
      ionCannon: 40,
      plasmaTurret: 18,
      smallShieldDome: true,
      largeShieldDome: true,
      antiBallisticMissiles: 45,
      interplanetaryMissiles: 15,
    },
    lunarBase: {
      level: 4,
      sensorPhalanxLevel: 5,
      jumpGateLevel: 2,
      moonFieldsUsed: 12,
      moonFieldsMax: 25,
    },
  },
  {
    id: 'pl-1',
    name: 'Ironroot Deepdelve',
    coordinate: '1:12:4',
    biome: 'Moonstone Mountain Hold',
    level: 4,
    incomeBonus: 18500,
    defenseBonus: 32000,
    maintenanceCost: 13560,
    moonName: 'The Embervein',
    jumpGateLevel: 2,
    fieldsUsed: 52,
    fieldsMax: 165,
    temperature: '+4°C',
    diameterKm: 11200,
    hasMoon: true,
    metalProductionRate: 28000,
    crystalProductionRate: 19500,
    deuteriumProductionRate: 12400,
    naquadahProductionRate: 22000,
    energyProductionRate: 520,
    specialization: 'fortress',
    governor: 'Colonel Jack O\'Neill',
    taxPolicy: 'balanced',
    foodStockpile: 18000,
    foodCapacity: 60000,
    foodProductionRate: 6800,
    foodConsumptionRate: 4500,
    waterStockpile: 22000,
    waterCapacity: 75000,
    waterProductionRate: 9200,
    waterConsumptionRate: 5200,
    population: {
      total: 2400000,
      growthRatePerHour: 5800,
      housingCapacity: 4500000,
      happiness: 82,
      unrest: 16,
      strata: {
        farmers: 350000,
        hydrologists: 400000,
        miners: 650000,
        industrialWorkers: 400000,
        scientists: 250000,
        administrators: 100000,
        militaryRecruits: 250000,
      },
      livingStandard: 'decent',
      rationingLevel: 'abundant',
    },
    lifeSupportFacilities: {
      hydroponicsDomes: 6,
      bioFarms: 4,
      geneticCropLabs: 2,
      deepAquiferPumps: 8,
      moistureCondensers: 6,
      desalinationPlants: 4,
      subsurfaceCisterns: 7,
      atmosphereScrubbers: 5,
    },
    hazards: [
      {
        id: 'hzd-alpha-1',
        name: 'Frostfang Whiteout',
        type: 'cryo_frost',
        severity: 'moderate',
        icon: '❄️',
        effectDescription: 'Frigid mountain temperatures increase surface power consumption by 15% and slow exterior facility expansion.',
        habitabilityPenalty: 12,
        popGrowthPenalty: 10,
        waterContaminationPercent: 2,
        isMitigated: true,
        mitigationProjectName: 'Subterranean Thermal Tap Vents',
      },
    ],
    plunge: {
      plungeIndex: 14,
      stage: 'stable',
      trend: 'stable',
      reasons: ['Secure subterranean bunker complex', 'Stable food and geothermal water reserves'],
      activeCrises: [],
      interventionsAvailable: [
        {
          id: 'int-relief-drop-pl1',
          name: 'Harvest Relief Caravan',
          category: 'logistics',
          description: 'Deploy atmospheric cargo lifters to distribute 5,000 Food and 5,000 Water directly to strained sectors.',
          cost: { food: 5000, water: 5000, energy: 50 },
          plungeReduction: 12,
          happinessBonus: 10,
          cooldownMinutes: 15,
        },
      ],
    },
    facilities: {
      roboticsFactory: 5,
      shipyard: 6,
      researchLab: 8,
      allianceDepot: 2,
      missileSilo: 4,
      naniteFactory: 2,
      terraformer: 0,
    },
    mines: {
      metalMine: 18,
      crystalMine: 15,
      deuteriumSynthesizer: 14,
      solarPlant: 16,
      fusionReactor: 8,
      naquadahCoreTap: 12,
    },
    defenses: {
      rocketLauncher: 320,
      lightLaser: 150,
      heavyLaser: 60,
      gaussCannon: 24,
      ionCannon: 15,
      plasmaTurret: 6,
      smallShieldDome: true,
      largeShieldDome: false,
      antiBallisticMissiles: 20,
      interplanetaryMissiles: 5,
    },
    lunarBase: {
      level: 2,
      sensorPhalanxLevel: 3,
      jumpGateLevel: 1,
      moonFieldsUsed: 6,
      moonFieldsMax: 15,
    },
  },
  {
    id: 'pl-2',
    name: "Elderwood of Lethariel",
    coordinate: '1:44:8',
    biome: "Enchanted Silverwood",
    level: 2,
    incomeBonus: 10500,
    defenseBonus: 18500,
    maintenanceCost: 5950,
    moonName: "Moonwell Hollow",
    jumpGateLevel: 1,
    fieldsUsed: 38,
    fieldsMax: 142,
    temperature: '+32°C',
    diameterKm: 9800,
    hasMoon: true,
    metalProductionRate: 19000,
    crystalProductionRate: 12000,
    deuteriumProductionRate: 8500,
    naquadahProductionRate: 14000,
    energyProductionRate: 380,
    specialization: 'industrial',
    governor: "Warden Saelith",
    taxPolicy: 'balanced',
    foodStockpile: 9000,
    foodCapacity: 40000,
    foodProductionRate: 4100,
    foodConsumptionRate: 3800,
    waterStockpile: 8500,
    waterCapacity: 45000,
    waterProductionRate: 3900,
    waterConsumptionRate: 4200,
    population: {
      total: 1900000,
      growthRatePerHour: 2200,
      housingCapacity: 3000000,
      happiness: 64,
      unrest: 34,
      strata: {
        farmers: 280000,
        hydrologists: 220000,
        miners: 500000,
        industrialWorkers: 350000,
        scientists: 120000,
        administrators: 80000,
        militaryRecruits: 350000,
      },
      livingStandard: 'basic',
      rationingLevel: 'standard',
    },
    lifeSupportFacilities: {
      hydroponicsDomes: 4,
      bioFarms: 3,
      geneticCropLabs: 1,
      deepAquiferPumps: 4,
      moistureCondensers: 3,
      desalinationPlants: 2,
      subsurfaceCisterns: 4,
      atmosphereScrubbers: 3,
    },
    hazards: [
      {
        id: 'hzd-chulak-1',
        name: 'Solar Flare Radiation Burst & Atmospheric Thinning',
        type: 'solar_flare',
        severity: 'high',
        icon: '☀️',
        effectDescription: 'Unfiltered solar radiation bleaches surface farmlands and increases water evaporation rates.',
        habitabilityPenalty: 22,
        popGrowthPenalty: 18,
        waterContaminationPercent: 14,
        isMitigated: false,
        mitigationProjectName: 'Keep Magnetic Deflector Array',
        mitigationCost: { metal: 60000, crystal: 45000, deuterium: 20000, naquadah: 25000 },
      },
      {
        id: 'hzd-chulak-2',
        name: 'Arid Duststorms & Seasonal Drought',
        type: 'toxic_spore',
        severity: 'moderate',
        icon: '🌪️',
        effectDescription: 'Violent particulate storms clog surface moisture condensers.',
        habitabilityPenalty: 12,
        popGrowthPenalty: 10,
        waterContaminationPercent: 8,
        isMitigated: false,
        mitigationProjectName: 'Sealed Dome Electro-Filtration Grids',
        mitigationCost: { metal: 35000, crystal: 20000, deuterium: 10000, naquadah: 8000 },
      },
    ],
    plunge: {
      plungeIndex: 38,
      stage: 'stressed',
      trend: 'deteriorating',
      reasons: ['Net negative water production (-300/h deficit)', 'Active unmitigated solar radiation storms', 'Mounting civil unrest among warrior castes'],
      activeCrises: ['Impending Aquifer Depletion Crisis', 'Solar Radiation Sickness Flare'],
      interventionsAvailable: [
        {
          id: 'int-relief-drop-pl2',
          name: 'Harvest Relief Caravan',
          category: 'logistics',
          description: 'Deploy atmospheric cargo lifters to distribute 5,000 Food and 5,000 Water directly to strained sectors.',
          cost: { food: 5000, water: 5000, energy: 50 },
          plungeReduction: 12,
          happinessBonus: 10,
          cooldownMinutes: 15,
        },
        {
          id: 'int-peacekeeper-patrol-pl2',
          name: 'Crown Guard and Royal Watch Muster',
          category: 'martial',
          description: 'Deploy elite Jaffa and Tau\'ri security cadres to suppress black markets and quell civil unrest.',
          cost: { naquadah: 10000, metal: 12000 },
          plungeReduction: 18,
          happinessBonus: -4,
          cooldownMinutes: 20,
        },
      ],
    },
    facilities: {
      roboticsFactory: 4,
      shipyard: 4,
      researchLab: 4,
      allianceDepot: 1,
      missileSilo: 2,
      naniteFactory: 1,
      terraformer: 0,
    },
    mines: {
      metalMine: 14,
      crystalMine: 12,
      deuteriumSynthesizer: 10,
      solarPlant: 12,
      fusionReactor: 5,
      naquadahCoreTap: 8,
    },
    defenses: {
      rocketLauncher: 180,
      lightLaser: 80,
      heavyLaser: 30,
      gaussCannon: 12,
      ionCannon: 8,
      plasmaTurret: 2,
      smallShieldDome: true,
      largeShieldDome: false,
      antiBallisticMissiles: 10,
      interplanetaryMissiles: 0,
    },
    lunarBase: {
      level: 1,
      sensorPhalanxLevel: 2,
      jumpGateLevel: 1,
      moonFieldsUsed: 4,
      moonFieldsMax: 12,
    },
  },
  {
    id: 'pl-3',
    name: "Ironroot Deepdelve",
    coordinate: '2:5:3',
    biome: "Dwarven Mountain Hold",
    level: 3,
    incomeBonus: 22000,
    defenseBonus: 12000,
    maintenanceCost: 7490,
    moonName: "The Embervein",
    jumpGateLevel: 1,
    fieldsUsed: 44,
    fieldsMax: 155,
    temperature: '+58°C',
    diameterKm: 10500,
    hasMoon: true,
    metalProductionRate: 15000,
    crystalProductionRate: 34000,
    deuteriumProductionRate: 6000,
    naquadahProductionRate: 48000,
    energyProductionRate: 420,
    specialization: 'mining',
    governor: "Thane Brokk Ironroot",
    taxPolicy: 'extractive',
    foodStockpile: 6000,
    foodCapacity: 30000,
    foodProductionRate: 2200,
    foodConsumptionRate: 3100,
    waterStockpile: 5000,
    waterCapacity: 35000,
    waterProductionRate: 2400,
    waterConsumptionRate: 3500,
    population: {
      total: 1700000,
      growthRatePerHour: -450,
      housingCapacity: 2500000,
      happiness: 45,
      unrest: 56,
      strata: {
        farmers: 180000,
        hydrologists: 190000,
        miners: 850000,
        industrialWorkers: 220000,
        scientists: 80000,
        administrators: 60000,
        militaryRecruits: 120000,
      },
      livingStandard: 'impoverished',
      rationingLevel: 'strict_rationing',
    },
    lifeSupportFacilities: {
      hydroponicsDomes: 3,
      bioFarms: 2,
      geneticCropLabs: 0,
      deepAquiferPumps: 3,
      moistureCondensers: 2,
      desalinationPlants: 1,
      subsurfaceCisterns: 3,
      atmosphereScrubbers: 2,
    },
    hazards: [
      {
        id: 'hzd-abydos-1',
        name: 'Extreme Dune Hyperthermia (+58°C Surface Heat)',
        type: 'solar_flare',
        severity: 'high',
        icon: '🔥',
        effectDescription: 'Scorching daytime temperatures cause rapid water reservoir evaporation and worker heat exhaustion.',
        habitabilityPenalty: 28,
        popGrowthPenalty: 24,
        waterContaminationPercent: 20,
        isMitigated: false,
        mitigationProjectName: 'Sub-Sand Cooling Duct Complex',
        mitigationCost: { metal: 50000, crystal: 35000, deuterium: 15000, naquadah: 20000 },
      },
      {
        id: 'hzd-abydos-2',
        name: 'Shifting Silica Dune Migration',
        type: 'tectonic_fault',
        severity: 'moderate',
        icon: '🏜️',
        effectDescription: 'Mega sand waves bury perimeter mining roads and damage heavy extraction rigs.',
        habitabilityPenalty: 14,
        popGrowthPenalty: 12,
        waterContaminationPercent: 5,
        isMitigated: false,
        mitigationProjectName: 'Subsurface Dune Anchoring Anchors',
        mitigationCost: { metal: 30000, crystal: 15000, deuterium: 5000, naquadah: 10000 },
      },
    ],
    plunge: {
      plungeIndex: 58,
      stage: 'severe_crisis',
      trend: 'deteriorating',
      reasons: ['Dual Food (-900/h) and Water (-1,100/h) deficits', 'Extractive colonial tax policy causing worker fatigue', 'Extreme desert temperatures depleting moisture reserves'],
      activeCrises: ['Severe Famine Risk Alert', 'Impoverished Miner Labor Strike', 'Rapid Aquifer Desiccation'],
      interventionsAvailable: [
        {
          id: 'int-relief-drop-pl3',
          name: 'Harvest Relief Caravan',
          category: 'logistics',
          description: 'Deploy atmospheric cargo lifters to distribute 5,000 Food and 5,000 Water directly to strained sectors.',
          cost: { food: 5000, water: 5000, energy: 50 },
          plungeReduction: 12,
          happinessBonus: 10,
          cooldownMinutes: 15,
        },
        {
          id: 'int-welfare-stimulus-pl3',
          name: 'Royal Bread & Hearth Fund',
          category: 'welfare',
          description: 'Disburse 25,000 Crowns and credits to subsidize healthcare and colonial living standards.',
          cost: { naquadah: 25000, credits: 500 },
          plungeReduction: 15,
          happinessBonus: 14,
          cooldownMinutes: 30,
        },
        {
          id: 'int-peacekeeper-patrol-pl3',
          name: 'Crown Guard and Royal Watch Muster',
          category: 'martial',
          description: 'Deploy elite Jaffa and Tau\'ri security cadres to suppress black markets and quell civil unrest.',
          cost: { naquadah: 10000, metal: 12000 },
          plungeReduction: 18,
          happinessBonus: -4,
          cooldownMinutes: 20,
        },
      ],
    },
    facilities: {
      roboticsFactory: 3,
      shipyard: 3,
      researchLab: 5,
      allianceDepot: 1,
      missileSilo: 3,
      naniteFactory: 1,
      terraformer: 0,
    },
    mines: {
      metalMine: 12,
      crystalMine: 22,
      deuteriumSynthesizer: 8,
      solarPlant: 18,
      fusionReactor: 4,
      naquadahCoreTap: 20,
    },
    defenses: {
      rocketLauncher: 120,
      lightLaser: 60,
      heavyLaser: 20,
      gaussCannon: 8,
      ionCannon: 5,
      plasmaTurret: 2,
      smallShieldDome: false,
      largeShieldDome: false,
      antiBallisticMissiles: 8,
      interplanetaryMissiles: 0,
    },
    lunarBase: {
      level: 1,
      sensorPhalanxLevel: 1,
      jumpGateLevel: 1,
      moonFieldsUsed: 3,
      moonFieldsMax: 10,
    },
  },
];

export const INITIAL_MARKET_ORDERS: MarketOrder[] = [
  { id: 'mkt-1', sellerName: 'Rebel Jaffa Cartel', resourceType: 'naquadah', quantity: 250000, pricePerUnit: 1.0, totalCost: 250000 },
  { id: 'mkt-2', sellerName: 'Free Sylvan Court Guild', resourceType: 'super-weapon', quantity: 15, pricePerUnit: 14000, totalCost: 210000 },
  { id: 'mkt-3', sellerName: 'Tok\'ra Logistics', resourceType: 'energy-core', quantity: 5, pricePerUnit: 48000, totalCost: 240000 },
];

export const MERCENARY_CONTRACTS: MercenaryContract[] = [
  {
    id: 'merc-1',
    name: 'Free Jaffa Assault Cadre',
    type: 'infantry',
    attackPower: 120,
    defensePower: 80,
    cost: 18000,
    upkeepPerTurn: 450,
    available: 12,
  },
  {
    id: 'merc-2',
    name: 'Kull Warrior Biomechanical Unit',
    type: 'heavy',
    attackPower: 350,
    defensePower: 300,
    cost: 55000,
    upkeepPerTurn: 1200,
    available: 4,
  },
  {
    id: 'merc-3',
    name: 'Tok\'ra Symbiote Infiltrators',
    type: 'infiltrator',
    attackPower: 60,
    defensePower: 50,
    cost: 28000,
    upkeepPerTurn: 600,
    available: 8,
  },
];

export const INITIAL_RANKINGS: RankingEntry[] = [
  { rank: 1, commanderName: 'Queen Elowen Vale', race: 'Sylvan Court', overallScore: 245000, attackScore: 190000, defenseScore: 310000, covertScore: 180000, mothershipScore: 300000, glory: 4800 },
  { rank: 2, commanderName: 'Prince Kael Emberwing', race: "Ashen Dominion", overallScore: 212000, attackScore: 230000, defenseScore: 220000, covertScore: 205000, mothershipScore: 193000, glory: 3900 },
  { rank: 3, commanderName: 'Warden Aria Vale (You)', race: "Valewyn", overallScore: 168500, attackScore: 175000, defenseScore: 182000, covertScore: 142000, mothershipScore: 175000, glory: 1250 },
  { rank: 4, commanderName: 'High Marshal Darius Blackthorn', race: "Ashen Dominion", overallScore: 142000, attackScore: 155000, defenseScore: 140000, covertScore: 132000, mothershipScore: 141000, glory: 1100 },
  { rank: 5, commanderName: 'Thane Brokk Ironroot', race: 'Ironroot Clans', overallScore: 139000, attackScore: 125000, defenseScore: 130000, covertScore: 210000, mothershipScore: 91000, glory: 980 },
  { rank: 6, commanderName: 'Matriarch Vexa Ashhand', race: "Ashen Dominion", overallScore: 118000, attackScore: 110000, defenseScore: 125000, covertScore: 135000, mothershipScore: 102000, glory: 820 },
  { rank: 7, commanderName: 'Bra\'tac Free Council', race: 'Jaffa', overallScore: 95000, attackScore: 102000, defenseScore: 98000, covertScore: 78000, mothershipScore: 102000, glory: 690 },
];

export const INITIAL_ALLIANCES: Alliance[] = [
  { id: 'all-1', name: 'Tau\'ri Defense Coalition', tag: '[TDC]', leader: 'Warden Aria Vale', membersCount: 14, treasury: 1850000, isOpen: true },
  { id: 'all-2', name: 'The Ashen Banner Pact', tag: '[SL]', leader: 'High Marshal Darius Blackthorn', membersCount: 22, treasury: 4500000, isOpen: false },
  { id: 'all-3', name: 'The Silverwood Covenant', tag: '[APPA]', leader: 'Queen Elowen Vale', membersCount: 8, treasury: 6200000, isOpen: true },
];

export const INITIAL_MESSAGES: GameMessage[] = [
  {
    id: 'msg-1',
    sender: 'Queen Elowen Vale',
    recipient: 'Warden Aria Vale',
    subject: 'A Gift from the Silverwood Forge',
    body: 'Greetings, Champion. We have observed heightened Ironroot Clans activity in the eastern Marches. High-frequency shield modulators have been transferred to your armory reserves. Maintain vigilance.',
    timestamp: '14 minutes ago',
    read: false,
  },
  {
    id: 'msg-2',
    sender: 'The Royal Council',
    recipient: 'Warden Aria Vale',
    subject: 'The Crown’s Harvest Ledger',
    body: 'Champion, the the crown’s reeves on Ironroot Deepdelve reported 100% extraction efficiency. Verify your bank vault allocation to prevent overflow losses during upcoming turn cycles.',
    timestamp: '1 hour ago',
    read: true,
  },
];
