import {
  HyperspaceDriveTech,
  SubspaceJumpGate,
  WormholeAnomaly,
  MothershipTitanClass,
  MothershipTacticalAbility,
} from './types';

export const HYPERSPACE_DRIVES: HyperspaceDriveTech[] = [
  {
    id: 'drive_combustion',
    name: 'Bannerwind Harness',
    tier: 1,
    speedMultiplier: 1.0,
    fuelEfficiency: 1.0,
    deuteriumCostPerHour: 50,
    description: 'A rig of sailcloth, wind-runes, and counterweights that carries couriers and light craft over familiar roads.',
    level: 8,
  },
  {
    id: 'drive_impulse',
    name: 'Cloudwake Rig',
    tier: 2,
    speedMultiplier: 2.2,
    fuelEfficiency: 1.4,
    deuteriumCostPerHour: 120,
    description: 'A rune-lifted rig for fast river galleys and sky-barges, tuned to catch high winds without exhausting its crew.',
    level: 6,
  },
  {
    id: 'drive_hyperspace',
    name: 'Leyroad Wayfinder',
    tier: 3,
    speedMultiplier: 4.5,
    fuelEfficiency: 2.0,
    deuteriumCostPerHour: 280,
    description: 'A charting stone attuned to known waystones, guiding great war galleys swiftly between distant marches.',
    level: 5,
  },
  {
    id: 'drive_tachyon',
    name: 'Threshold Weaver',
    tier: 4,
    speedMultiplier: 8.0,
    fuelEfficiency: 3.2,
    deuteriumCostPerHour: 550,
    description: 'A masterwork loom binds two familiar roads for a brief crossing, carrying a prepared host beyond ordinary reach.',
    level: 3,
  },
  {
    id: 'drive_slipstream',
    name: 'Crownstone of the Old Road',
    tier: 5,
    speedMultiplier: 15.0,
    fuelEfficiency: 5.0,
    deuteriumCostPerHour: 1100,
    description: 'An ancient crownstone opens forgotten leyroads between far realms, but only for a host sworn to its passage.',
    level: 2,
  },
];

export const INITIAL_JUMP_GATES: SubspaceJumpGate[] = [
  {
    id: 'gate-1',
    name: 'Eastridge Waystone Pair',
    originMoon: 'Eastridge Gatehouse',
    destinationMoon: 'Northwatch Keep',
    chargePercentage: 100,
    ready: true,
    cooldownSeconds: 0,
  },
  {
    id: 'gate-2',
    name: 'Northwatch Rootgate',
    originMoon: 'Northwatch Keep',
    destinationMoon: 'Silverwood Underhall',
    chargePercentage: 74,
    ready: false,
    cooldownSeconds: 156,
  },
  {
    id: 'gate-3',
    name: 'Nine-Crown Leygate',
    originMoon: 'Eastridge Gatehouse',
    destinationMoon: 'Sunspire Sanctuary',
    chargePercentage: 100,
    ready: true,
    cooldownSeconds: 0,
  },
];

export const WORMHOLE_ANOMALIES: WormholeAnomaly[] = [
  {
    id: 'wormhole-alpha',
    name: 'Gloamveil Thornwake',
    stability: 'stable',
    destinationSector: 'Shattered Barrows: The First Keep',
    dangerRating: 'low',
    rewardPotential: 'High (Moonstone Reliquaries and Oath-Iron)',
    durationSeconds: 1800,
  },
  {
    id: 'wormhole-beta',
    name: 'The Hourglass Barrow',
    stability: 'fluctuating',
    destinationSector: 'Timeworn March: The Unburied Hall',
    dangerRating: 'moderate',
    rewardPotential: 'Extreme (Lost Warforge Patterns and Elder Relics)',
    durationSeconds: 940,
  },
  {
    id: 'wormhole-gamma',
    name: 'The Emberfall Wound',
    stability: 'critical',
    destinationSector: 'Emberfall Crucible: The Hollow Threshold',
    dangerRating: 'extreme',
    rewardPotential: 'Legendary (Dawnshards and Ancient Crownstones)',
    durationSeconds: 320,
  },
];

export const MOTHERSHIP_TITAN_CLASSES: MothershipTitanClass[] = [
  {
    id: 'class_dreadnought',
    name: 'Crownward Citadel Barge',
    hullType: 'dreadnought',
    hullHp: 1500000,
    shieldHp: 950000,
    firepower: 480000,
    energyCore: 12000,
    hangarSlots: 8,
    flagshipBonus: '+20% Warband Volley Power',
    description: 'An iron-ribbed command barge with a warded deck, heavy ballistae, and room for veteran companies.',
  },
  {
    id: 'class_titan',
    name: 'Starfall Covenant Skyhold',
    hullType: 'titan',
    hullHp: 3200000,
    shieldHp: 2800000,
    firepower: 950000,
    energyCore: 25000,
    hangarSlots: 14,
    flagshipBonus: '+40% Warband Wards and Faster Renewal',
    description: 'A fortress-barge built from starfall iron and dragon-glass, guarded by layered oath-runes and skilled wardwrights.',
  },
  {
    id: 'class_colossus',
    name: 'Ember-Crowned Siege Ark',
    hullType: 'colossus',
    hullHp: 5500000,
    shieldHp: 3500000,
    firepower: 1850000,
    energyCore: 40000,
    hangarSlots: 20,
    flagshipBonus: '+50% Siege Might and Keep Ward Breach',
    description: 'A vast, many-tiered war temple carrying a gate-breaking ram and the engines of a long siege.',
  },
  {
    id: 'class_world_eater',
    name: 'The Oldroot Bastion',
    hullType: 'world_eater',
    hullHp: 9000000,
    shieldHp: 6500000,
    firepower: 3200000,
    energyCore: 80000,
    hangarSlots: 32,
    flagshipBonus: 'Recovers 50% of lost arms and stores for the host',
    description: 'A legendary moving stronghold whose deep vaults and guild crews recover useful arms after a battle.',
  },
];

export const MOTHERSHIP_TACTICAL_ABILITIES: MothershipTacticalAbility[] = [
  {
    id: 'ability_orbital_beam',
    name: 'Crownfire Lance',
    energyCost: 1500,
    cooldownSeconds: 60,
    remainingCooldown: 0,
    icon: '⚡',
    description: 'Calls a focused shaft of dragonfire against a marked engine, gate, or siege tower.',
    effectType: 'bombardment',
  },
  {
    id: 'ability_shield_overcharge',
    name: 'Hearthward Aegis',
    energyCost: 1200,
    cooldownSeconds: 45,
    remainingCooldown: 0,
    icon: '🛡️',
    description: 'Kindles the barge’s wardstones, turning aside incoming arrows, spellfire, and engine-shot for a short time.',
    effectType: 'shield_overcharge',
  },
  {
    id: 'ability_warp_jump',
    name: 'Waystone Refuge',
    energyCost: 2000,
    cooldownSeconds: 90,
    remainingCooldown: 0,
    icon: '🌀',
    description: 'Binds the host to a nearby known waystone and withdraws it from a closing ambush.',
    effectType: 'warp_jump',
  },
  {
    id: 'ability_sensor_sweep',
    name: 'Lanterns of the March',
    energyCost: 800,
    cooldownSeconds: 30,
    remainingCooldown: 0,
    icon: '📡',
    description: 'Lights a chain of lookout beacons, revealing hostile warbands moving through neighboring holdings.',
    effectType: 'sensor_sweep',
  },
  {
    id: 'ability_fleet_aura',
    name: 'Banner of Nine Oaths',
    energyCost: 1000,
    cooldownSeconds: 60,
    remainingCooldown: 0,
    icon: '👑',
    description: 'A shared battle-song steadies every sworn company, improving aim and coordinated strikes by 35%.',
    effectType: 'fleet_aura',
  },
];
