import {
  OGameTechnology,
  OGameFacility,
  OGameShip,
  OGameDefense,
  FleetFormation,
  FleetFormationPreset,
  MegastructureProject,
  ExpeditionLog,
  ExpeditionMission,
} from './types';

// =========================================================================
// 1. OGAME MASTER RESEARCH LIBRARY & TECH TREE
// =========================================================================
export const OGAME_TECHNOLOGIES: OGameTechnology[] = [
  // --- ECONOMICS & MINING BRANCH ---
  {
    id: 'basic_engineering',
    name: "Keepwright's Foundations",
    branch: 'economics',
    category: 'materials',
    description: 'The measured craft of raising keeps, roads, mills, and sound foundations from local stone and timber.',
    level: 1,
    maxLevel: 50,
    baseCost: { metal: 200, crystal: 100, deuterium: 0, energy: 10 },
    costMultiplier: 1.5,
    baseTimeSeconds: 15,
    prerequisites: [],
    effects: [
      { type: 'production_boost', label: 'Builders’ Pace', valuePerLevel: 5, unit: '%' },
    ],
    unlockTargets: ['Ironroot Deep Mine Lv 2', 'Guild Mechanists’ Hall'],
  },
  {
    id: 'mineral_processing',
    name: 'Orecraft',
    branch: 'economics',
    category: 'mining',
    description: 'Wash, sort, and refine raw ore into dependable iron bars, clear stone, and smithing stock.',
    level: 1,
    maxLevel: 50,
    baseCost: { metal: 400, crystal: 200, deuterium: 50, energy: 20 },
    costMultiplier: 1.6,
    baseTimeSeconds: 25,
    prerequisites: [{ type: 'tech', id: 'basic_engineering', name: "Keepwright's Foundations", requiredLevel: 1 }],
    effects: [
      { type: 'production_boost', label: 'Ironroot Mine Yield', valuePerLevel: 6, unit: '%' },
    ],
    unlockTargets: ['Ore-Sorting Hall', 'Deepdelve Prospecting'],
  },
  {
    id: 'deep_core_mining',
    name: 'Deepdelve Prospecting',
    branch: 'economics',
    category: 'mining',
    description: 'Survey deep mountain seams with braced shafts, waterwheels, and rune-marked fault maps.',
    level: 0,
    maxLevel: 40,
    baseCost: { metal: 1200, crystal: 800, deuterium: 300, energy: 50 },
    costMultiplier: 1.7,
    baseTimeSeconds: 50,
    prerequisites: [{ type: 'tech', id: 'mineral_processing', name: 'Orecraft', requiredLevel: 2 }],
    effects: [
      { type: 'production_boost', label: 'Deep Seam Yield', valuePerLevel: 8, unit: '%' },
    ],
    unlockTargets: ['Rare Vein Survey', 'Skyfall Orecraft'],
  },
  {
    id: 'asteroid_mining',
    name: 'Skyfall Orecraft',
    branch: 'economics',
    category: 'mining',
    description: 'Track fallen star-iron across high ridges and bring the scattered ore safely to a forge.',
    level: 0,
    maxLevel: 30,
    baseCost: { metal: 4000, crystal: 2500, deuterium: 1200, energy: 100 },
    costMultiplier: 1.75,
    baseTimeSeconds: 90,
    prerequisites: [
      { type: 'tech', id: 'deep_core_mining', name: 'Deepdelve Prospecting', requiredLevel: 3 },
      { type: 'tech', id: 'ion_propulsion', name: 'Skyfaring', requiredLevel: 2 },
    ],
    effects: [
      { type: 'production_boost', label: 'Far-March Ore Yield', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Skyfall Ore Cart', 'Far-March Surveying'],
  },

  // --- ENERGY BRANCH ---
  {
    id: 'energy_science',
    name: 'Leyline Studies',
    branch: 'science',
    category: 'energy',
    description: 'Study the currents beneath hearth, grove, and mountain, learning how to gather and safely direct their power.',
    level: 1,
    maxLevel: 50,
    baseCost: { metal: 0, crystal: 800, deuterium: 400, energy: 0 },
    costMultiplier: 1.5,
    baseTimeSeconds: 20,
    prerequisites: [],
    effects: [
      { type: 'energy_boost', label: 'Leyline Efficiency', valuePerLevel: 4, unit: '%' },
    ],
    unlockTargets: ['Dawnmirror Lore', 'Dragonheart Alchemy', 'Sunlance Craft'],
  },
  {
    id: 'solar_energy',
    name: 'Dawnmirror Lore',
    branch: 'science',
    category: 'energy',
    description: 'Shape polished mirrors to gather the first light of dawn and warm a holding through the long winter.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 300, crystal: 500, deuterium: 100, energy: 0 },
    costMultiplier: 1.55,
    baseTimeSeconds: 30,
    prerequisites: [{ type: 'tech', id: 'energy_science', name: 'Leyline Studies', requiredLevel: 1 }],
    effects: [
      { type: 'energy_boost', label: 'Dawnmirror Yield', valuePerLevel: 7, unit: '%' },
    ],
    unlockTargets: ['Dawnmirror Garden', 'Sunward Beacon Tower'],
  },
  {
    id: 'fusion_energy',
    name: 'Dragonheart Alchemy',
    branch: 'science',
    category: 'energy',
    description: 'A sealed dragon-glass crucible binds a fierce, steady flame to a carefully drawn ward-circle.',
    level: 0,
    maxLevel: 40,
    baseCost: { metal: 1600, crystal: 1400, deuterium: 1000, energy: 0 },
    costMultiplier: 1.65,
    baseTimeSeconds: 60,
    prerequisites: [{ type: 'tech', id: 'energy_science', name: 'Leyline Studies', requiredLevel: 3 }],
    effects: [
      { type: 'energy_boost', label: 'Dragonheart Crucible Yield', valuePerLevel: 12, unit: '%' },
    ],
    unlockTargets: ['Dragonheart Crucible', 'Skyfaring', 'Ironbound War Galley'],
  },
  {
    id: 'antimatter_tech',
    name: 'Voidflame Rite',
    branch: 'advanced_science',
    category: 'energy',
    description: 'A perilous rite that gathers cold voidfire inside layered runes; only veteran keepers may tend its flame.',
    level: 0,
    maxLevel: 30,
    baseCost: { metal: 8000, crystal: 12000, deuterium: 9000, energy: 500 },
    costMultiplier: 1.8,
    baseTimeSeconds: 160,
    prerequisites: [
      { type: 'tech', id: 'fusion_energy', name: 'Dragonheart Alchemy', requiredLevel: 5 },
      { type: 'tech', id: 'quantum_computing', name: 'Runescript Calculus', requiredLevel: 3 },
    ],
    effects: [
      { type: 'energy_boost', label: 'Voidflame Yield', valuePerLevel: 18, unit: '%' },
      { type: 'weapon_boost', label: 'Voidflame Strike', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Voidflame Crucible', 'Riftfire Bolt', 'Oathbound Dreadnought'],
  },
  {
    id: 'zero_point_energy',
    name: 'Hearth of First Light',
    branch: 'endgame',
    category: 'energy',
    description: 'Legendary hearth-lore draws a calm, inexhaustible ember from the first spark named in the oldest songs.',
    level: 0,
    maxLevel: 20,
    baseCost: { metal: 50000, crystal: 80000, deuterium: 60000, energy: 2000 },
    costMultiplier: 2.0,
    baseTimeSeconds: 360,
    prerequisites: [
      { type: 'tech', id: 'antimatter_tech', name: 'Voidflame Rite', requiredLevel: 6 },
      { type: 'tech', id: 'dimensional_propulsion', name: 'Threshold Weaving', requiredLevel: 4 },
    ],
    effects: [
      { type: 'energy_boost', label: 'Realmwide Hearth Surplus', valuePerLevel: 25, unit: '%' },
    ],
    unlockTargets: ['First-Light Hearth', 'Crownland Citadel', 'Dawnmirror Crown'],
  },

  // --- SCIENCE & COMPUTING BRANCH ---
  {
    id: 'computer_technology',
    name: 'Scriptorium Networks',
    branch: 'science',
    category: 'computing',
    description: 'Linked scriptoria, signal fires, and courier posts carry orders between distant holdings without delay.',
    level: 1,
    maxLevel: 50,
    baseCost: { metal: 0, crystal: 400, deuterium: 600, energy: 10 },
    costMultiplier: 1.5,
    baseTimeSeconds: 25,
    prerequisites: [],
    effects: [
      { type: 'fleet_slot', label: 'Active Warband Orders', valuePerLevel: 1, unit: 'slots' },
    ],
    unlockTargets: ['War Council Dispatches', 'Guild Warforge', 'Master Scriptorium'],
  },
  {
    id: 'quantum_computing',
    name: 'Runescript Calculus',
    branch: 'advanced_science',
    category: 'computing',
    description: 'Scribes compare branching rune-patterns to plan many marches, harvests, and ward-lines at once.',
    level: 0,
    maxLevel: 35,
    baseCost: { metal: 2000, crystal: 4500, deuterium: 3000, energy: 50 },
    costMultiplier: 1.7,
    baseTimeSeconds: 80,
    prerequisites: [{ type: 'tech', id: 'computer_technology', name: 'Scriptorium Networks', requiredLevel: 5 }],
    effects: [
      { type: 'research_speed', label: 'Lore Study Pace', valuePerLevel: 8, unit: '%' },
      { type: 'fleet_slot', label: 'Advanced Warband Orders', valuePerLevel: 1, unit: 'slots' },
    ],
    unlockTargets: ['Bound Guardian Craft', 'Runeward Lattices', 'High Scriptorium'],
  },
  {
    id: 'artificial_intelligence',
    name: 'Bound Guardian Craft',
    branch: 'advanced_science',
    category: 'ai',
    description: 'Bind a golem to a narrow, freely chosen duty: keep watch, carry a message, or hold a gate in battle.',
    level: 0,
    maxLevel: 25,
    baseCost: { metal: 6000, crystal: 10000, deuterium: 7500, energy: 120 },
    costMultiplier: 1.8,
    baseTimeSeconds: 140,
    prerequisites: [{ type: 'tech', id: 'quantum_computing', name: 'Runescript Calculus', requiredLevel: 4 }],
    effects: [
      { type: 'weapon_boost', label: 'Guardian Coordination', valuePerLevel: 6, unit: '%' },
      { type: 'speed_boost', label: 'Golem Response Time', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Disciplined Warband Formations', 'Runeglyph Great Forge Lv 2'],
  },

  // --- PROPULSION BRANCH ---
  {
    id: 'chemical_propulsion',
    name: 'Bannerwind Craft',
    branch: 'military',
    category: 'propulsion',
    description: 'Read wind, river, and road to move messengers, carts, and light craft swiftly between holdings.',
    level: 1,
    maxLevel: 30,
    baseCost: { metal: 200, crystal: 400, deuterium: 200, energy: 0 },
    costMultiplier: 1.5,
    baseTimeSeconds: 20,
    prerequisites: [],
    effects: [
      { type: 'speed_boost', label: 'Caravan and Courier Pace', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Roadward Cart', 'Lantern Scout', 'Light Warband'],
  },
  {
    id: 'ion_propulsion',
    name: 'Skyfaring',
    branch: 'military',
    category: 'propulsion',
    description: 'Master sail, rope, and lift-runes to guide sky barges and swift patrol craft through high winds.',
    level: 0,
    maxLevel: 30,
    baseCost: { metal: 1000, crystal: 2000, deuterium: 800, energy: 30 },
    costMultiplier: 1.6,
    baseTimeSeconds: 45,
    prerequisites: [
      { type: 'tech', id: 'chemical_propulsion', name: 'Bannerwind Craft', requiredLevel: 2 },
      { type: 'tech', id: 'energy_science', name: 'Leyline Studies', requiredLevel: 2 },
    ],
    effects: [
      { type: 'speed_boost', label: 'Sky-Barge and Patrol Pace', valuePerLevel: 15, unit: '%' },
    ],
    unlockTargets: ['Blacksteel Sky-Barge', 'Marcher Galley', 'Ironbound War Galley', 'Delver’s Salvage Cart'],
  },
  {
    id: 'hyperspace_drive',
    name: 'Leyroad Wayfinding',
    branch: 'advanced_fleet',
    category: 'propulsion',
    description: 'Arcanists chart old ley-lines and teach royal couriers to travel swiftly between known waystones.',
    level: 0,
    maxLevel: 25,
    baseCost: { metal: 8000, crystal: 15000, deuterium: 12000, energy: 200 },
    costMultiplier: 1.75,
    baseTimeSeconds: 150,
    prerequisites: [
      { type: 'tech', id: 'ion_propulsion', name: 'Skyfaring', requiredLevel: 4 },
      { type: 'tech', id: 'fusion_energy', name: 'Dragonheart Alchemy', requiredLevel: 4 },
    ],
    effects: [
      { type: 'speed_boost', label: 'Royal Retinue March Speed', valuePerLevel: 20, unit: '%' },
    ],
    unlockTargets: ['Ironbound War Galley', 'Royal Sky-Barge', 'Crown Guard Retinue', 'Leygate Waystone'],
  },
  {
    id: 'dimensional_propulsion',
    name: 'Threshold Weaving',
    branch: 'endgame',
    category: 'dimensional',
    description: 'Bind two known waystones with a temporary path, allowing a prepared retinue to cross a great distance.',
    level: 0,
    maxLevel: 15,
    baseCost: { metal: 45000, crystal: 70000, deuterium: 50000, energy: 1500 },
    costMultiplier: 2.1,
    baseTimeSeconds: 320,
    prerequisites: [
      { type: 'tech', id: 'hyperspace_drive', name: 'Leyroad Wayfinding', requiredLevel: 6 },
      { type: 'tech', id: 'quantum_computing', name: 'Runescript Calculus', requiredLevel: 6 },
    ],
    effects: [
      { type: 'speed_boost', label: 'Realmwide Retinue March Speed', valuePerLevel: 30, unit: '%' },
    ],
    unlockTargets: ['Crownward Flagships', 'Paired Leygates', 'Far-March Passage'],
  },

  // --- WEAPONS BRANCH ---
  {
    id: 'kinetic_weapons',
    name: 'Armscraft',
    branch: 'military',
    category: 'weapons',
    description: 'Train bowyers, fletchers, and engineers to shape reliable bows, crossbows, and wall-mounted engines.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 600, crystal: 200, deuterium: 0, energy: 0 },
    costMultiplier: 1.5,
    baseTimeSeconds: 25,
    prerequisites: [],
    effects: [
      { type: 'weapon_boost', label: 'Bow and Engine Power', valuePerLevel: 8, unit: '%' },
    ],
    unlockTargets: ['Wall Ballista', 'Stone-Thrower Battery', 'Light Warband Arms'],
  },
  {
    id: 'laser_technology',
    name: 'Sunlance Craft',
    branch: 'military',
    category: 'weapons',
    description: 'Focus sunlight through cut crystal and polished silver to forge a lance of searing, ward-breaking light.',
    level: 0,
    maxLevel: 35,
    baseCost: { metal: 1000, crystal: 800, deuterium: 200, energy: 40 },
    costMultiplier: 1.6,
    baseTimeSeconds: 40,
    prerequisites: [{ type: 'tech', id: 'energy_science', name: 'Leyline Studies', requiredLevel: 2 }],
    effects: [
      { type: 'weapon_boost', label: 'Sunlance Force', valuePerLevel: 9, unit: '%' },
    ],
    unlockTargets: ['Sunlance Emplacement', 'High Sunlance', 'War Galley Lightcaster'],
  },
  {
    id: 'plasma_technology',
    name: 'Dragonfire Craft',
    branch: 'military',
    category: 'weapons',
    description: 'Temper dragon-glass and alchemical oil into a contained flame potent enough to breach a fortress ward.',
    level: 0,
    maxLevel: 30,
    baseCost: { metal: 4000, crystal: 3000, deuterium: 2000, energy: 100 },
    costMultiplier: 1.7,
    baseTimeSeconds: 85,
    prerequisites: [
      { type: 'tech', id: 'laser_technology', name: 'Sunlance Craft', requiredLevel: 4 },
      { type: 'tech', id: 'fusion_energy', name: 'Dragonheart Alchemy', requiredLevel: 3 },
    ],
    effects: [
      { type: 'weapon_boost', label: 'Dragonfire Engine Power', valuePerLevel: 12, unit: '%' },
    ],
    unlockTargets: ['Dragonfire Engine', 'Great Dragonfire Engine', 'War Galley Firedeck'],
  },

  // --- SHIELDS & DEFENSE BRANCH ---
  {
    id: 'shield_technology',
    name: 'Runeward Craft',
    branch: 'military',
    category: 'shields',
    description: 'Carve protective signs into gates, shields, and stonework so a holding can withstand a long siege.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 200, crystal: 600, deuterium: 300, energy: 50 },
    costMultiplier: 1.55,
    baseTimeSeconds: 30,
    prerequisites: [{ type: 'tech', id: 'energy_science', name: 'Leyline Studies', requiredLevel: 2 }],
    effects: [
      { type: 'shield_boost', label: 'Warband and Holding Wards', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Gate Ward', 'Great Keep Ward', 'War Galley Runescreens'],
  },
  {
    id: 'armor_technology',
    name: 'Oathmail Craft',
    branch: 'military',
    category: 'armor',
    description: 'Layer mail, leather, and oath-iron plates to protect a champion without slowing the whole warband.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 800, crystal: 0, deuterium: 100, energy: 0 },
    costMultiplier: 1.5,
    baseTimeSeconds: 25,
    prerequisites: [{ type: 'tech', id: 'basic_engineering', name: "Keepwright's Foundations", requiredLevel: 2 }],
    effects: [
      { type: 'armor_boost', label: 'Warband Armor', valuePerLevel: 10, unit: '%' },
    ],
    unlockTargets: ['Reinforced Oathmail', 'Blacksteel Harness'],
  },
  {
    id: 'phase_shields',
    name: 'Veilbound Wards',
    branch: 'advanced_science',
    category: 'shields',
    description: 'Layer a moving veil over existing wards to turn aside hostile spellwork and misdirect a charging foe.',
    level: 0,
    maxLevel: 25,
    baseCost: { metal: 6000, crystal: 12000, deuterium: 8000, energy: 300 },
    costMultiplier: 1.8,
    baseTimeSeconds: 150,
    prerequisites: [
      { type: 'tech', id: 'shield_technology', name: 'Runeward Craft', requiredLevel: 5 },
      { type: 'tech', id: 'quantum_computing', name: 'Runescript Calculus', requiredLevel: 3 },
    ],
    effects: [
      { type: 'shield_boost', label: 'Veil Ward Strength', valuePerLevel: 15, unit: '%' },
    ],
    unlockTargets: ['Citadel Veilward', 'Crownward Aegis'],
  },

  // --- ESPIONAGE & COLONIZATION ---
  {
    id: 'espionage_technology',
    name: 'Lantern Scoutcraft',
    branch: 'science',
    category: 'espionage',
    description: 'Train scouts to read tracks, plant listening posts, carry sealed messages, and leave false trails.',
    level: 1,
    maxLevel: 40,
    baseCost: { metal: 100, crystal: 500, deuterium: 200, energy: 20 },
    costMultiplier: 1.5,
    baseTimeSeconds: 25,
    prerequisites: [{ type: 'tech', id: 'computer_technology', name: 'Scriptorium Networks', requiredLevel: 1 }],
    effects: [
      { type: 'expedition_slot', label: 'Scout Reach and Counter-Signs', valuePerLevel: 1, unit: 'slots' },
    ],
    unlockTargets: ['Lantern Scout', 'Watchtower Signal Chain', 'Long-March Reconnaissance'],
  },
  {
    id: 'astrophysics',
    name: 'March Lore & Expeditions',
    branch: 'science',
    category: 'colonization',
    description: 'Study weather, river crossings, old maps, and waystone marks before leading an expedition beyond the marches.',
    level: 1,
    maxLevel: 30,
    baseCost: { metal: 4000, crystal: 8000, deuterium: 4000, energy: 100 },
    costMultiplier: 1.75,
    baseTimeSeconds: 120,
    prerequisites: [
      { type: 'tech', id: 'espionage_technology', name: 'Lantern Scoutcraft', requiredLevel: 3 },
      { type: 'tech', id: 'ion_propulsion', name: 'Skyfaring', requiredLevel: 3 },
    ],
    effects: [
      { type: 'expedition_slot', label: 'Concurrent March Charters', valuePerLevel: 1, unit: 'slots' },
    ],
    unlockTargets: ['Settler’s Caravan', 'Deep-March Expeditions', 'Refugee Waytrain'],
  },

  // --- MEGASTRUCTURES BRANCH ---
  {
    id: 'stellar_engineering',
    name: 'Greatwork Masonry',
    branch: 'megastructures',
    category: 'megastructure',
    description: 'Unite guilds, masons, and wardwrights to raise lasting wonders that serve every holding in a realm.',
    level: 0,
    maxLevel: 15,
    baseCost: { metal: 100000, crystal: 150000, deuterium: 100000, energy: 5000 },
    costMultiplier: 2.2,
    baseTimeSeconds: 600,
    prerequisites: [
      { type: 'tech', id: 'zero_point_energy', name: 'Hearth of First Light', requiredLevel: 2 },
      { type: 'tech', id: 'dimensional_propulsion', name: 'Threshold Weaving', requiredLevel: 3 },
    ],
    effects: [
      { type: 'production_boost', label: 'Greatwork Construction Rate', valuePerLevel: 20, unit: '%' },
    ],
    unlockTargets: ['Dawnmirror Crown', 'Crownland Citadel', 'Worldroot Sanctuary', 'High Warforge'],
  },
];

// =========================================================================
// 2. INDUSTRIAL FACILITIES & FACTORIES
// =========================================================================
export const OGAME_FACILITIES: OGameFacility[] = [
  // Resource Facilities
  {
    id: 'metal_mine',
    name: 'Ironroot Deep Mine',
    category: 'resource',
    description: 'Braced shafts and waterwheels bring iron, star-steel, and oath-iron ore up from the deep seams.',
    level: 3,
    maxLevel: 50,
    baseCost: { metal: 60, crystal: 15, deuterium: 0 },
    costMultiplier: 1.5,
    energyConsumptionPerLevel: 10,
    productionPerLevel: { metal: 120 },
    bonusDescription: '+120 Iron / minute per level',
    prerequisites: [],
  },
  {
    id: 'crystal_mine',
    name: 'Moonstone Quarry',
    category: 'resource',
    description: 'Careful quarry crews cut moonstone and clear quartz from the mountain heart for lenses and rune-work.',
    level: 2,
    maxLevel: 50,
    baseCost: { metal: 48, crystal: 24, deuterium: 0 },
    costMultiplier: 1.6,
    energyConsumptionPerLevel: 12,
    productionPerLevel: { crystal: 80 },
    bonusDescription: '+80 Moonstone / minute per level',
    prerequisites: [],
  },
  {
    id: 'deuterium_synthesizer',
    name: 'Aetherwell Distillery',
    category: 'resource',
    description: 'Alchemists draw aether-rich salts from deep water and refine them into stable leyline fuel.',
    level: 1,
    maxLevel: 45,
    baseCost: { metal: 225, crystal: 75, deuterium: 0 },
    costMultiplier: 1.5,
    energyConsumptionPerLevel: 20,
    productionPerLevel: { deuterium: 45 },
    bonusDescription: '+45 Aether / minute per level',
    prerequisites: [],
  },

  // Power Plants
  {
    id: 'solar_plant',
    name: 'Dawnmirror Garden',
    category: 'resource',
    description: 'Rows of polished dawn-mirrors gather sunlight and feed steady warmth into the holding leyline.',
    level: 4,
    maxLevel: 50,
    baseCost: { metal: 75, crystal: 30, deuterium: 0 },
    costMultiplier: 1.5,
    energyConsumptionPerLevel: 0,
    productionPerLevel: { energy: 75 },
    bonusDescription: '+75 Leyline power generated per level',
    prerequisites: [],
  },
  {
    id: 'fusion_reactor',
    name: 'Dragonheart Crucible',
    category: 'resource',
    description: 'A sealed dragon-glass hearth consumes refined Aether to kindle a powerful, carefully warded flame.',
    level: 0,
    maxLevel: 35,
    baseCost: { metal: 900, crystal: 360, deuterium: 180 },
    costMultiplier: 1.8,
    energyConsumptionPerLevel: 0,
    productionPerLevel: { energy: 240, deuterium: -15 },
    bonusDescription: '+240 Leyline power (consumes 15 Aether/minute) per level',
    prerequisites: [
      { type: 'tech', id: 'fusion_energy', name: 'Dragonheart Alchemy', requiredLevel: 1 },
    ],
  },

  // Manufacturing & Industrial Complex
  {
    id: 'robotics_factory',
    name: 'Guild Mechanists’ Hall',
    category: 'manufacturing',
    description: 'Master mechanists, geared cranes, and rune-guided jigs speed construction across the holding.',
    level: 2,
    maxLevel: 30,
    baseCost: { metal: 400, crystal: 120, deuterium: 200 },
    costMultiplier: 2.0,
    energyConsumptionPerLevel: 5,
    bonusDescription: 'Reduces facility building time by 10% per level',
    prerequisites: [
      { type: 'tech', id: 'basic_engineering', name: "Keepwright's Foundations", requiredLevel: 1 },
    ],
  },
  {
    id: 'nanite_factory',
    name: 'Runeglyph Great Forge',
    category: 'manufacturing',
    description: 'A master forge whose inscribed tools and tireless bound-work crews shorten major construction projects.',
    level: 0,
    maxLevel: 15,
    baseCost: { metal: 20000, crystal: 40000, deuterium: 10000 },
    costMultiplier: 2.0,
    energyConsumptionPerLevel: 50,
    bonusDescription: 'Halves major build times per level through compound rune-work',
    prerequisites: [
      { type: 'facility', id: 'robotics_factory', name: 'Guild Mechanists’ Hall', requiredLevel: 10 },
      { type: 'tech', id: 'computer_technology', name: 'Scriptorium Networks', requiredLevel: 10 },
    ],
  },
  {
    id: 'shipyard_facility',
    name: 'Royal Warforge Docks',
    category: 'manufacturing',
    description: 'Covered river docks and great timber slips build war galleys, sky barges, and merchant haulers.',
    level: 2,
    maxLevel: 30,
    baseCost: { metal: 400, crystal: 200, deuterium: 100 },
    costMultiplier: 2.0,
    energyConsumptionPerLevel: 15,
    bonusDescription: 'Unlocks advanced ship classes and increases shipyard queue slots',
    prerequisites: [
      { type: 'facility', id: 'robotics_factory', name: 'Guild Mechanists’ Hall', requiredLevel: 2 },
    ],
  },
  {
    id: 'research_lab',
    name: 'Arcanist Scriptorium',
    category: 'infrastructure',
    description: 'A quiet hall of map rooms, observatories, and sealed libraries where royal scholars test new lore.',
    level: 2,
    maxLevel: 30,
    baseCost: { metal: 200, crystal: 400, deuterium: 200 },
    costMultiplier: 2.0,
    energyConsumptionPerLevel: 20,
    bonusDescription: 'Increases research progression speed and unlocks advanced disciplines',
    prerequisites: [],
  },
];

// =========================================================================
// 3. SHIPYARD FLEET CATALOG (CIVILIAN, COMBAT, CARRIERS, CAPITAL)
// =========================================================================
export const OGAME_SHIPS: OGameShip[] = [
  // --- CIVILIAN SHIPS ---
  {
    id: 'small_cargo',
    name: 'Crownroad Pack Cart',
    category: 'civilian',
    description: 'A nimble covered cart that carries provisions and reclaimed goods along the Crownroad.',
    structure: 4000,
    shield: 10,
    weaponPower: 5,
    cargoCapacity: 5000,
    speed: 5000,
    fuelConsumption: 10,
    cost: { metal: 2000, crystal: 2000, deuterium: 0 },
    buildTimeSeconds: 15,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 2 },
      { type: 'tech', id: 'chemical_propulsion', name: 'Bannerwind Craft', requiredLevel: 2 },
    ],
    rapidfireAgainst: {},
    quantity: 12,
  },
  {
    id: 'large_cargo',
    name: 'Amber Road Caravan',
    category: 'civilian',
    description: 'A long train of guarded wagons carrying harvest, timber, ore, and treasury chests between great markets.',
    structure: 12000,
    shield: 25,
    weaponPower: 5,
    cargoCapacity: 25000,
    speed: 7500,
    fuelConsumption: 50,
    cost: { metal: 6000, crystal: 6000, deuterium: 0 },
    buildTimeSeconds: 35,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 4 },
      { type: 'tech', id: 'chemical_propulsion', name: 'Bannerwind Craft', requiredLevel: 4 },
    ],
    rapidfireAgainst: {},
    quantity: 4,
  },
  {
    id: 'colony_ship',
    name: 'Hearthsettler Wagon',
    category: 'civilian',
    description: 'A self-sufficient waytrain bearing families, seed grain, tools, and a charter for a new frontier holding.',
    structure: 30000,
    shield: 100,
    weaponPower: 50,
    cargoCapacity: 7500,
    speed: 2500,
    fuelConsumption: 1000,
    cost: { metal: 10000, crystal: 20000, deuterium: 10000 },
    buildTimeSeconds: 120,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 4 },
      { type: 'tech', id: 'astrophysics', name: 'March Lore & Expeditions', requiredLevel: 3 },
    ],
    rapidfireAgainst: {},
    quantity: 1,
  },
  {
    id: 'recycler',
    name: "Delver's Salvage Cart",
    category: 'civilian',
    description: 'A reinforced salvage train with cranes and sorting bins for recovering useful craft from ruined keeps.',
    structure: 16000,
    shield: 10,
    weaponPower: 1,
    cargoCapacity: 20000,
    speed: 4000,
    fuelConsumption: 300,
    cost: { metal: 10000, crystal: 6000, deuterium: 2000 },
    buildTimeSeconds: 45,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 4 },
      { type: 'tech', id: 'ion_propulsion', name: 'Skyfaring', requiredLevel: 2 },
    ],
    rapidfireAgainst: {},
    quantity: 2,
  },
  {
    id: 'espionage_probe',
    name: 'Lantern Scout',
    category: 'civilian',
    description: 'A small, well-trained scout party that marks trails, counts sentries, and returns with a sealed report.',
    structure: 1000,
    shield: 0,
    weaponPower: 0,
    cargoCapacity: 5,
    speed: 100000,
    fuelConsumption: 1,
    cost: { metal: 0, crystal: 1000, deuterium: 0 },
    buildTimeSeconds: 5,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 3 },
      { type: 'tech', id: 'espionage_technology', name: 'Lantern Scoutcraft', requiredLevel: 2 },
    ],
    rapidfireAgainst: {},
    quantity: 15,
  },

  // --- COMBAT SHIPS ---
  {
    id: 'light_fighter',
    name: 'Light Warband',
    category: 'combat',
    description: 'A quick company of spearmen and bowhands trained to outpace heavier foes and seize a narrow pass.',
    structure: 4000,
    shield: 10,
    weaponPower: 50,
    cargoCapacity: 50,
    speed: 12500,
    fuelConsumption: 20,
    cost: { metal: 3000, crystal: 1000, deuterium: 0 },
    buildTimeSeconds: 20,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 1 },
      { type: 'tech', id: 'chemical_propulsion', name: 'Bannerwind Craft', requiredLevel: 1 },
    ],
    rapidfireAgainst: { espionage_probe: 5 },
    quantity: 25,
  },
  {
    id: 'heavy_fighter',
    name: 'Blacksteel Vanguard',
    category: 'combat',
    description: 'A veteran shield-and-spear company clad in blacksteel, built to hold the front when lighter troops fall back.',
    structure: 10000,
    shield: 25,
    weaponPower: 150,
    cargoCapacity: 100,
    speed: 10000,
    fuelConsumption: 75,
    cost: { metal: 6000, crystal: 4000, deuterium: 0 },
    buildTimeSeconds: 40,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 3 },
      { type: 'tech', id: 'armor_technology', name: 'Oathmail Craft', requiredLevel: 2 },
      { type: 'tech', id: 'ion_propulsion', name: 'Skyfaring', requiredLevel: 2 },
    ],
    rapidfireAgainst: { small_cargo: 3, espionage_probe: 5 },
    quantity: 10,
  },
  {
    id: 'cruiser',
    name: 'Marcher Galley',
    category: 'combat',
    description: 'A swift river galley carrying archers and wardwrights to reinforce crossings before an enemy arrives.',
    structure: 27000,
    shield: 50,
    weaponPower: 400,
    cargoCapacity: 800,
    speed: 15000,
    fuelConsumption: 300,
    cost: { metal: 20000, crystal: 7000, deuterium: 2000 },
    buildTimeSeconds: 75,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 5 },
      { type: 'tech', id: 'ion_propulsion', name: 'Skyfaring', requiredLevel: 4 },
      { type: 'tech', id: 'heavy_laser', name: 'Sunlance Craft', requiredLevel: 3 },
    ],
    rapidfireAgainst: { light_fighter: 6, espionage_probe: 5, rocket_launcher: 10 },
    quantity: 6,
  },
  {
    id: 'battleship',
    name: 'Ironbound War Galley',
    category: 'combat',
    description: 'A deep-hulled war galley with layered oak, iron-rimmed shields, and a broad deck for veteran archers.',
    structure: 60000,
    shield: 200,
    weaponPower: 1000,
    cargoCapacity: 1500,
    speed: 10000,
    fuelConsumption: 500,
    cost: { metal: 45000, crystal: 15000, deuterium: 0 },
    buildTimeSeconds: 150,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 7 },
      { type: 'tech', id: 'hyperspace_drive', name: 'Leyroad Wayfinding', requiredLevel: 4 },
    ],
    rapidfireAgainst: { espionage_probe: 5 },
    quantity: 2,
  },
  {
    id: 'battlecruiser',
    name: 'Crownward Longship',
    category: 'combat',
    description: 'A long, fast command vessel that slips past a shieldwall to challenge an enemy captain directly.',
    structure: 70000,
    shield: 400,
    weaponPower: 700,
    cargoCapacity: 750,
    speed: 10000,
    fuelConsumption: 250,
    cost: { metal: 30000, crystal: 40000, deuterium: 15000 },
    buildTimeSeconds: 180,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 8 },
      { type: 'tech', id: 'hyperspace_drive', name: 'Leyroad Wayfinding', requiredLevel: 5 },
      { type: 'tech', id: 'laser_technology', name: 'Sunlance Craft', requiredLevel: 6 },
    ],
    rapidfireAgainst: { espionage_probe: 5, small_cargo: 3, large_cargo: 3, heavy_fighter: 4, cruiser: 4, battleship: 7 },
    quantity: 1,
  },

  // --- CARRIER FLEET ---
  {
    id: 'fleet_carrier',
    name: 'Royal Sky-Barge',
    category: 'carrier',
    description: 'A vast rune-lifted barge with a sheltered deck for scout craft, healers, and reserve companies.',
    structure: 120000,
    shield: 600,
    weaponPower: 350,
    cargoCapacity: 3000,
    speed: 8000,
    fuelConsumption: 600,
    cost: { metal: 80000, crystal: 60000, deuterium: 25000 },
    buildTimeSeconds: 240,
    hangarCapacity: 120,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 9 },
      { type: 'tech', id: 'hyperspace_drive', name: 'Leyroad Wayfinding', requiredLevel: 6 },
      { type: 'tech', id: 'computer_technology', name: 'Scriptorium Networks', requiredLevel: 8 },
    ],
    rapidfireAgainst: { light_fighter: 8, espionage_probe: 5 },
    quantity: 0,
  },

  // --- CAPITAL & TITANS ---
  {
    id: 'dreadnought',
    name: 'Oathbound Dreadnought',
    category: 'capital',
    description: 'An immense siege galley clad in oath-iron, carrying a ward-breaking ram and a company of veteran breakers.',
    structure: 250000,
    shield: 1500,
    weaponPower: 3200,
    cargoCapacity: 5000,
    speed: 6000,
    fuelConsumption: 1200,
    cost: { metal: 150000, crystal: 100000, deuterium: 50000 },
    buildTimeSeconds: 400,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 10 },
      { type: 'tech', id: 'antimatter_tech', name: 'Voidflame Rite', requiredLevel: 3 },
      { type: 'tech', id: 'plasma_technology', name: 'Dragonfire Craft', requiredLevel: 5 },
    ],
    rapidfireAgainst: { cruiser: 7, battleship: 5, defense_turret: 15 },
    quantity: 0,
  },
  {
    id: 'titan_flagship',
    name: 'Crownland Citadel',
    category: 'capital',
    description: 'A legendary moving fortress, built from the joined craft of every crown and warded to shelter an entire host.',
    structure: 1000000,
    shield: 8000,
    weaponPower: 15000,
    cargoCapacity: 20000,
    speed: 4000,
    fuelConsumption: 5000,
    cost: { metal: 800000, crystal: 500000, deuterium: 300000 },
    buildTimeSeconds: 900,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 12 },
      { type: 'tech', id: 'zero_point_energy', name: 'Hearth of First Light', requiredLevel: 2 },
      { type: 'tech', id: 'dimensional_propulsion', name: 'Threshold Weaving', requiredLevel: 2 },
    ],
    rapidfireAgainst: { battleship: 10, dreadnought: 4, light_fighter: 25, heavy_laser: 20 },
    quantity: 0,
  },
];

// =========================================================================
// 4. PLANETARY DEFENSE GRID (OGAME SPEC SECTION 22)
// =========================================================================
export const OGAME_DEFENSES: OGameDefense[] = [
  {
    id: 'rocket_launcher',
    name: 'Crownroad Firepot Crew',
    category: 'kinetic',
    description: 'Wall crews hurl sealed firepots and pitch-soaked quarrels at attackers massing beyond bowshot.',
    structure: 2000,
    shield: 20,
    weaponPower: 80,
    cost: { metal: 2000, crystal: 0, deuterium: 0 },
    buildTimeSeconds: 10,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 1 },
    ],
    quantity: 30,
  },
  {
    id: 'light_laser',
    name: 'Sunlance Wall Emplacement',
    category: 'laser',
    description: 'A crystal-lensed wall engine that focuses a quick flash of sunlight against fast-moving raiders.',
    structure: 2000,
    shield: 25,
    weaponPower: 100,
    cost: { metal: 1500, crystal: 500, deuterium: 0 },
    buildTimeSeconds: 15,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 2 },
      { type: 'tech', id: 'energy_science', name: 'Leyline Studies', requiredLevel: 1 },
      { type: 'tech', id: 'laser_technology', name: 'Sunlance Craft', requiredLevel: 1 },
    ],
    quantity: 15,
  },
  {
    id: 'heavy_laser',
    name: 'High Sunlance Battery',
    category: 'laser',
    description: 'A heavily warded crystal engine whose concentrated beam can split siege mantlets and crack plate.',
    structure: 8000,
    shield: 100,
    weaponPower: 250,
    cost: { metal: 6000, crystal: 2000, deuterium: 0 },
    buildTimeSeconds: 30,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 4 },
      { type: 'tech', id: 'energy_science', name: 'Leyline Studies', requiredLevel: 3 },
      { type: 'tech', id: 'laser_technology', name: 'Sunlance Craft', requiredLevel: 3 },
    ],
    quantity: 6,
  },
  {
    id: 'gauss_cannon',
    name: 'Stone-Thrower Battery',
    category: 'kinetic',
    description: 'A counterweighted engine hurls stone shot into shieldwalls, siege towers, and heavy field fortifications.',
    structure: 35000,
    shield: 200,
    weaponPower: 1100,
    cost: { metal: 20000, crystal: 15000, deuterium: 2000 },
    buildTimeSeconds: 60,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 6 },
      { type: 'tech', id: 'kinetic_weapons', name: 'Armscraft', requiredLevel: 5 },
      { type: 'tech', id: 'shield_technology', name: 'Runeward Craft', requiredLevel: 3 },
    ],
    quantity: 2,
  },
  {
    id: 'plasma_turret',
    name: 'Dragonfire Wall Engine',
    category: 'plasma',
    description: 'A rare dragon-glass engine releases a brief, searing gout of alchemical flame across the siege line.',
    structure: 100000,
    shield: 300,
    weaponPower: 3000,
    cost: { metal: 50000, crystal: 50000, deuterium: 30000 },
    buildTimeSeconds: 120,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 8 },
      { type: 'tech', id: 'plasma_technology', name: 'Dragonfire Craft', requiredLevel: 5 },
    ],
    quantity: 1,
  },
  {
    id: 'small_shield_dome',
    name: 'Gate Wardstone',
    category: 'shield',
    description: 'A rune-cut standing stone projects a close ward around a gatehouse and its defenders.',
    structure: 20000,
    shield: 2000,
    weaponPower: 0,
    cost: { metal: 10000, crystal: 10000, deuterium: 0 },
    buildTimeSeconds: 60,
    maxBuildable: 1,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 1 },
      { type: 'tech', id: 'shield_technology', name: 'Runeward Craft', requiredLevel: 2 },
    ],
    quantity: 1,
  },
  {
    id: 'large_shield_dome',
    name: 'Citadel Veilward',
    category: 'shield',
    description: 'A linked circle of wardstones shields a citadel from engines, spellfire, and a determined siege host.',
    structure: 100000,
    shield: 10000,
    weaponPower: 0,
    cost: { metal: 50000, crystal: 50000, deuterium: 0 },
    buildTimeSeconds: 150,
    maxBuildable: 1,
    prerequisites: [
      { type: 'facility', id: 'shipyard_facility', name: 'Royal Warforge Docks', requiredLevel: 6 },
      { type: 'tech', id: 'shield_technology', name: 'Runeward Craft', requiredLevel: 6 },
    ],
    quantity: 0,
  },
];

// =========================================================================
// 5. FLEET FORMATIONS (SPEC SECTION 25)
// =========================================================================
export const FLEET_FORMATIONS: FleetFormation[] = [
  {
    id: 'standard',
    name: 'Crownroad March',
    description: 'A steady column keeps scouts, wagons, and the main warband within call of one another.',
    attackModifier: 1.0,
    defenseModifier: 1.0,
    speedModifier: 1.0,
    flagshipProtection: 1.0,
  },
  {
    id: 'line',
    name: 'Shieldwall Line',
    description: 'A locked front of shields and spear-points trades speed for a disciplined push through the center.',
    attackModifier: 1.25,
    defenseModifier: 0.9,
    speedModifier: 0.85,
    flagshipProtection: 1.1,
  },
  {
    id: 'wedge',
    name: 'Pikehead Wedge',
    description: 'A narrow spearhead drives into a weak point and tries to divide the enemy line.',
    attackModifier: 1.35,
    defenseModifier: 0.8,
    speedModifier: 1.15,
    flagshipProtection: 0.85,
  },
  {
    id: 'defensive',
    name: 'Hearthward Perimeter',
    description: 'A guarded ring protects the baggage, wounded, and banner while warders cover the approaches.',
    attackModifier: 0.85,
    defenseModifier: 1.35,
    speedModifier: 0.9,
    flagshipProtection: 1.5,
  },
  {
    id: 'assault',
    name: 'Skirmisher Ring',
    description: 'Small bands feint from several paths, drawing defenders out before the main company closes.',
    attackModifier: 1.15,
    defenseModifier: 1.1,
    speedModifier: 1.2,
    flagshipProtection: 0.95,
  },
  {
    id: 'carrier',
    name: 'Sky-Barge Vanguard',
    description: 'The sky-barge stays behind the shieldwall while scouts and outriders range ahead.',
    attackModifier: 1.2,
    defenseModifier: 1.2,
    speedModifier: 0.95,
    flagshipProtection: 1.6,
  },
];

// =========================================================================
// 6. MEGASTRUCTURE PROJECTS (SPEC SECTION 30)
// =========================================================================
export const MEGASTRUCTURE_PROJECTS: MegastructureProject[] = [
  {
    id: 'dyson_swarm',
    name: 'Dawnmirror Crown',
    subtitle: 'Realmwide Sunward Works',
    description: 'A chain of polished mirrors on high ridges gathers dawnlight and carries warmth to the realm’s hearths.',
    icon: '☀️',
    currentStage: 0,
    totalStages: 3,
    isConstructing: false,
    constructionRemainingSeconds: 0,
    grandBenefit: '+50,000 Leyline Power and +30% realmwide resource production',
    prerequisites: [
      { type: 'tech', id: 'stellar_engineering', name: 'Greatwork Masonry', requiredLevel: 1 },
      { type: 'tech', id: 'solar_energy', name: 'Dawnmirror Lore', requiredLevel: 5 },
    ],
    stages: [
      {
        stageNumber: 1,
        name: 'Stage I: Eastridge Mirror Road',
        cost: { metal: 250000, crystal: 150000, deuterium: 50000 },
        durationSeconds: 180,
        completed: false,
        effectDescription: '+10,000 Energy',
      },
      {
        stageNumber: 2,
        name: 'Stage II: Sunward Ridge Mirrors',
        cost: { metal: 500000, crystal: 300000, deuterium: 100000 },
        durationSeconds: 240,
        completed: false,
        effectDescription: '+25,000 Energy',
      },
      {
        stageNumber: 3,
        name: 'Stage III: Crown of First Light',
        cost: { metal: 1000000, crystal: 600000, deuterium: 200000 },
        durationSeconds: 360,
        completed: false,
        effectDescription: '+50,000 Energy & +30% Mine Output',
      },
    ],
  },
  {
    id: 'orbital_ring',
    name: 'Nine-Crown Ringroad',
    subtitle: 'A Great Road for Every Holding',
    description: 'A warded circuit of roads, bridges, and fortified market keeps joins the farthest holdings to the heartland.',
    icon: '🪐',
    currentStage: 0,
    totalStages: 3,
    isConstructing: false,
    constructionRemainingSeconds: 0,
    grandBenefit: '+50% Holding Defense, +4 Warforge Queues, +25% Population Growth',
    prerequisites: [
      { type: 'tech', id: 'stellar_engineering', name: 'Greatwork Masonry', requiredLevel: 2 },
    ],
    stages: [
      {
        stageNumber: 1,
        name: 'Stage I: Eastridge Gate Foundations',
        cost: { metal: 300000, crystal: 200000, deuterium: 80000 },
        durationSeconds: 200,
        completed: false,
        effectDescription: '+15% Holding Defense and Supply',
      },
      {
        stageNumber: 2,
        name: 'Stage II: Nine-Crown Bridgeworks',
        cost: { metal: 600000, crystal: 400000, deuterium: 150000 },
        durationSeconds: 300,
        completed: false,
        effectDescription: '+2 Warforge Queues and +20% Population',
      },
      {
        stageNumber: 3,
        name: 'Stage III: Crownward Bastions',
        cost: { metal: 1200000, crystal: 800000, deuterium: 300000 },
        durationSeconds: 420,
        completed: false,
        effectDescription: 'The Ringroad’s great keeps and wards are joined',
      },
    ],
  },
  {
    id: 'galactic_gateway',
    name: 'Twin Leygates of the Old Road',
    subtitle: 'Paired Waystones',
    description: 'Two ancient standing stones are bound to a known road, letting a prepared retinue cross the realm in moments.',
    icon: '🌀',
    currentStage: 0,
    totalStages: 2,
    isConstructing: false,
    constructionRemainingSeconds: 0,
    grandBenefit: 'Near-instant retinue travel between linked waystones without Aether cost',
    prerequisites: [
      { type: 'tech', id: 'stellar_engineering', name: 'Greatwork Masonry', requiredLevel: 3 },
      { type: 'tech', id: 'dimensional_propulsion', name: 'Threshold Weaving', requiredLevel: 2 },
    ],
    stages: [
      {
        stageNumber: 1,
        name: 'Stage I: Oath of the First Waystone',
        cost: { metal: 500000, crystal: 400000, deuterium: 250000 },
        durationSeconds: 240,
        completed: false,
        effectDescription: 'The paired stones answer one another',
      },
      {
        stageNumber: 2,
        name: 'Stage II: Leyroad Oathbinding',
        cost: { metal: 1000000, crystal: 800000, deuterium: 500000 },
        durationSeconds: 380,
        completed: false,
        effectDescription: 'The old road opens to sworn retinues',
      },
    ],
  },
];

// =========================================================================
// 7. EXPEDITION ENCOUNTER OUTCOMES & INITIAL LOGS
// =========================================================================
export const INITIAL_EXPEDITION_LOGS: ExpeditionLog[] = [
  {
    id: 'exp-1',
    timestamp: '11:15:02',
    sector: 'Cinder March: Ashenford Pass',
    missionType: 'anomaly',
    status: 'triumph',
    narrative: 'A Crownroad Warden party found an abandoned Ironroot ore train beneath a rockslide and recovered its sealed stores.',
    loot: {
      metal: 35000,
      crystal: 22000,
      deuterium: 8000,
      naquadah: 15000,
    },
  },
  {
    id: 'exp-2',
    timestamp: '10:42:19',
    sector: 'Silverwood Reach: Moonwell Crossing',
    missionType: 'relic_discovery',
    status: 'discovery',
    narrative: 'Lantern Cartographers followed a faint song to a broken waystone and uncovered an intact moonstone reliquary.',
    loot: {
      crystal: 40000,
      relicName: 'First-Light Emberstone',
    },
  },
  {
    id: 'exp-3',
    timestamp: '09:20:55',
    sector: 'Eastridge Marches: Three Wells Moor',
    missionType: 'exploration',
    status: 'triumph',
    narrative: 'Delvers mapped a cold spring and a rich seam of iron beneath an untouched ridge above Three Wells Moor.',
    loot: {
      metal: 18000,
      deuterium: 14000,
    },
  },
];

export const INITIAL_FLEET_PRESETS: FleetFormationPreset[] = [
  {
    id: 'preset_rapid_scout',
    name: 'Lantern Warden Patrol',
    description: 'A light scouting party travels with enough guards and supplies to chart a dangerous road.',
    formation: 'standard',
    composition: {
      espionage_probe: 5,
      small_cargo: 2,
      light_fighter: 5,
    },
    createdAt: 1700000000000,
    tags: ['expedition', 'custom'],
  },
  {
    id: 'preset_heavy_assault',
    name: 'Ashen Pikehost',
    description: 'A disciplined shieldwall and veteran vanguard prepared to break a fortified march.',
    formation: 'line',
    composition: {
      battleship: 10,
      battlecruiser: 5,
      cruiser: 15,
      heavy_fighter: 25,
      light_fighter: 40,
    },
    createdAt: 1700000001000,
    tags: ['attack', 'custom'],
  },
  {
    id: 'preset_deep_salvage',
    name: 'Ironroot Delvers’ Train',
    description: 'Ore carts and salvage crews travel inside a guarded ring to recover craft from a ruined hold.',
    formation: 'defensive',
    composition: {
      large_cargo: 10,
      small_cargo: 15,
      recycler: 5,
      espionage_probe: 3,
      cruiser: 4,
    },
    createdAt: 1700000002000,
    tags: ['expedition', 'custom'],
  },
  {
    id: 'preset_penetration_wedge',
    name: 'Crownroad Breach Host',
    description: 'A pikehead of veteran breakers and siege crews presses through a warded gate.',
    formation: 'wedge',
    composition: {
      bomber: 8,
      destroyer: 6,
      cruiser: 12,
      heavy_fighter: 20,
    },
    createdAt: 1700000003000,
    tags: ['attack', 'custom'],
  },
  {
    id: 'preset_titan_armada',
    name: 'Nine-Crown Warhost',
    description: 'A legendary host marches beneath the Crownland Citadel’s banner with galleys, sky-barges, and sworn champions.',
    formation: 'carrier',
    composition: {
      titan_flagship: 1,
      dreadnought: 2,
      battleship: 6,
      carrier: 3,
      cruiser: 10,
      heavy_fighter: 30,
    },
    createdAt: 1700000004000,
    tags: ['attack', 'custom'],
  },
];

export const INITIAL_OGAME_TECHNOLOGIES: OGameTechnology[] = OGAME_TECHNOLOGIES;
export const INITIAL_OGAME_FACILITIES: OGameFacility[] = OGAME_FACILITIES;
export const INITIAL_OGAME_SHIPS: OGameShip[] = OGAME_SHIPS;
export const INITIAL_OGAME_DEFENSES: OGameDefense[] = OGAME_DEFENSES;
export const INITIAL_MEGASTRUCTURES: MegastructureProject[] = MEGASTRUCTURE_PROJECTS;
export const INITIAL_EXPEDITIONS: ExpeditionMission[] = [];
export const INITIAL_FLEET_FORMATION_PRESETS: FleetFormationPreset[] = INITIAL_FLEET_PRESETS;
