/**
 * Stargate Canonical NPC Races Database
 * Comprehensive dossiers, combat statistics, technological tiers, and diplomatic profiles
 * for 18 authentic alien civilizations from Stargate SG-1, Atlantis, and Universe.
 */

import { StargateNpcRace, TargetRealm } from './types';

const PRECURSOR_CIVILIZATIONS: StargateNpcRace[] = [
  // 1. THE ORI & PRIORS
  {
    id: 'npc_ori_priors',
    name: 'The Ori & Priors',
    designationOrTitle: 'Ascended Zealots of Origin',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Ori Galaxy',
    homeworld: 'Celestis (Plains of Celestis)',
    stargateAddress: 'ᚠ-ᚱ-ᛟ-ᛏ-ᛖ-ᛈ-ᛉ-ᛊ-ᛋ (Supergate Dial)',
    classification: 'Higher Energy / Ascended',
    threatLevel: 'Extinction Level / Cataclysmic',
    diplomaticStatus: 'Hostile',
    factionLeader: 'The Doci / Orici Adria',
    flagshipClass: 'Ori Crusader Warship (Primary Golden Pulse Beam)',
    fleetStrength: 850000,
    tacticalTraits: [
      'Devastating Spinal Energy Weapon (One-Shot Kills on Ha\'tak)',
      'Impenetrable Trans-Dimensional Energy Shields',
      'Prior Staff Telekinesis & Biological Pathogen Propagation',
      'Supergate Cosmic Ingress Network',
    ],
    loreDescription:
      'Ascended beings who sap the worship energy of mortal civilizations across the Ori Galaxy. Led through the Milky Way by the Priors and the Orici Adria, their golden-curved armada wields near-godlike destructive power.',
    firstAppearanceEpisode: 'SG-1 S09E01 "Avalon" & S09E02 "Origin"',
    combatStats: {
      attackBonusPercent: 85,
      shieldHarmonicsPercent: 95,
      sensorStealthPercent: 40,
      technologicalTier: 10,
    },
    resourceLoot: {
      naquadah: 950000,
      metalOrTrinium: 650000,
      crystal: 500000,
      deuterium: 400000,
    },
    avatarEmoji: '✨',
    sigilColor: '#f59e0b',
  },

  // 2. THE WRAITH
  {
    id: 'npc_wraith_hive',
    name: 'The Wraith',
    designationOrTitle: 'Predatory Hive Swarm of Pegasus',
    canonicalSeries: 'Stargate Atlantis',
    galaxy: 'Pegasus',
    homeworld: 'Unknown Hive Nursery Planet',
    stargateAddress: 'ᛈ-ᛖ-ᚷ-ᚨ-ᛋ-ᚢ-ᛋ-ᛉ',
    classification: 'Organic Humanoid',
    threatLevel: 'Extinction Level / Cataclysmic',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Todd the Wraith / Hive Queen Death',
    flagshipClass: 'Wraith Super-Hive Dreadnought (Bio-Organic Armor)',
    fleetStrength: 680000,
    tacticalTraits: [
      'Bio-Organic Hull Self-Regeneration without Shields',
      'Subspace Telepathic Hive Mind Coordination',
      'Dart Culling Beams with Digital Transporter Buffer Storage',
      'Energy Disruption Projectiles & Heavy Plasma Volleys',
    ],
    loreDescription:
      'A carnivorous, semi-telepathic species that evolved from the Iratus bug feeding on human ancestors. Dominating the Pegasus Galaxy for 10,000 years, they periodically awaken from hibernation cycles to cull populated worlds for life-force nourishment.',
    firstAppearanceEpisode: 'SGA S01E01 "Rising"',
    combatStats: {
      attackBonusPercent: 70,
      shieldHarmonicsPercent: 30,
      sensorStealthPercent: 55,
      technologicalTier: 8,
    },
    resourceLoot: {
      naquadah: 520000,
      metalOrTrinium: 480000,
      crystal: 380000,
      deuterium: 310000,
    },
    avatarEmoji: '🧬',
    sigilColor: '#10b981',
  },

  // 3. THE ASURANS (PEGASUS REPLICATORS)
  {
    id: 'npc_asuran_replicators',
    name: 'The Asurans',
    designationOrTitle: 'Lantean Nanite Collective',
    canonicalSeries: 'Stargate Atlantis',
    galaxy: 'Pegasus',
    homeworld: 'Asuras',
    stargateAddress: 'ᚨ-ᛋ-ᚢ-ᚱ-ᚨ-ᛋ-ᛏ-ᚱ',
    classification: 'Synthetic / Nanite',
    threatLevel: 'Extinction Level / Cataclysmic',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Oberoth / Niam (Subversive Faction)',
    flagshipClass: 'Asuran Aurora-Class Warship with Drone Arsenal',
    fleetStrength: 750000,
    tacticalTraits: [
      'Microscopic Nanite Reconstitution & Subspace Collective Mind',
      'Ancient Drone Weapons with Target-Tracking Agility',
      'ZPM-Powered Overcharged Stargate Energy Cannons',
      'Subspace Satellite Weapons Arrays',
    ],
    loreDescription:
      'Created by the Ancients during the Wraith War as a microscopic weapon made of nanites. Evolving into human form, they built sprawling cities mimicking Atlantis on their homeworld Asuras before rejecting their creators\' aggression-override code.',
    firstAppearanceEpisode: 'SGA S03E05 "Progeny"',
    combatStats: {
      attackBonusPercent: 80,
      shieldHarmonicsPercent: 88,
      sensorStealthPercent: 60,
      technologicalTier: 9,
    },
    resourceLoot: {
      naquadah: 750000,
      metalOrTrinium: 600000,
      crystal: 700000,
      deuterium: 350000,
    },
    avatarEmoji: '🤖',
    sigilColor: '#06b6d4',
  },

  // 4. THE ANCIENTS (LANTEANS / ALTERANS)
  {
    id: 'npc_ancients_lanteans',
    name: 'The Ancients (Lanteans)',
    designationOrTitle: 'The Builders of the Gate Network',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Dakara / P3X-984 / Atlantis',
    stargateAddress: 'ᛞ-ᚨ-ᚲ-ᚨ-ᚱ-ᚨ-ᛈ-ᛏ-ᛉ',
    classification: 'Higher Energy / Ascended',
    threatLevel: 'Harmless / Pacifist',
    diplomaticStatus: 'Ascended / Beyond Contact',
    factionLeader: 'High Councilor Moros / Janus / Oma Desala',
    flagshipClass: 'City-Ship Atlantis / Destiny / Aurora-Class',
    fleetStrength: 990000,
    tacticalTraits: [
      'Sub-atomic Zero Point Energy Harnessing (ZPMs)',
      'Drone Weapon Swarms that Penetrate Any Conventional Shield',
      'Super-luminal Stargate & Supergate Bridge Networks',
      'Cloaking Phase-Shifting Dimensional Tech',
    ],
    loreDescription:
      'The Alterans who migrated from their distant home galaxy millions of years ago, seeded human life across the Milky Way and Pegasus, invented the Stargate system, and ultimately ascended to higher planes of existence.',
    firstAppearanceEpisode: 'SG-1 S01E10 "The Torment of Tantalus"',
    combatStats: {
      attackBonusPercent: 95,
      shieldHarmonicsPercent: 98,
      sensorStealthPercent: 90,
      technologicalTier: 10,
    },
    resourceLoot: {
      naquadah: 1200000,
      metalOrTrinium: 900000,
      crystal: 1500000,
      deuterium: 800000,
    },
    avatarEmoji: '🏛️',
    sigilColor: '#3b82f6',
  },

  // 5. THE NOX
  {
    id: 'npc_the_nox',
    name: 'The Nox',
    designationOrTitle: 'The Enigmatic Pacifists',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Gaia (P3X-774)',
    stargateAddress: 'ᚷ-ᚨ-ᛁ-ᚨ-ᛈ-ᛏ-ᛉ',
    classification: 'Organic Humanoid',
    threatLevel: 'Harmless / Pacifist',
    diplomaticStatus: 'Neutral',
    factionLeader: 'Ohper / Lya / Nafrayu',
    flagshipClass: 'Cloaked Floating Spire Citadel',
    fleetStrength: 450000,
    tacticalTraits: [
      'Total Planetary & Orbital Cloaking (Imperceptible to Sensors)',
      'Biological Resurrection ("Ritual of Life")',
      'Zero-Delay Phase Invisibility for Armed Fleets',
      'Absolute Pacifism Doctrine (Never Fires Weapons)',
    ],
    loreDescription:
      'One of the legendary Four Great Races. Despite appearing as primitive, fairy-like forest dwellers living in harmony with nature, they possess cloaked floating sky-cities with technology so advanced they consider humans mere children.',
    firstAppearanceEpisode: 'SG-1 S01E08 "The Nox"',
    combatStats: {
      attackBonusPercent: 10,
      shieldHarmonicsPercent: 99,
      sensorStealthPercent: 100,
      technologicalTier: 9,
    },
    resourceLoot: {
      naquadah: 300000,
      metalOrTrinium: 400000,
      crystal: 650000,
      deuterium: 200000,
    },
    avatarEmoji: '🌿',
    sigilColor: '#84cc16',
  },

  // 6. THE FURLINGS
  {
    id: 'npc_furlings',
    name: 'The Furlings',
    designationOrTitle: 'The Enigmatic Architects',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Utopian Sanctuary (P5X-777)',
    stargateAddress: 'ᚠ-ᚢ-ᚱ-ᛚ-ᛁ-ᛜ-ᛈ',
    classification: 'Organic Humanoid',
    threatLevel: 'Harmless / Pacifist',
    diplomaticStatus: 'Neutral',
    factionLeader: 'Archon of the Great Alliance',
    flagshipClass: 'Quantum Archway Megastructure / Colony Transport',
    fleetStrength: 520000,
    tacticalTraits: [
      'Sub-molecular Teleportation Arches',
      'Bio-Synthetic Botanical Megastructures',
      'Quantum Pacification Fields',
      'Ancient Furling Writing & Tri-Planar Locking Devices',
    ],
    loreDescription:
      'The mysterious fourth member of the Great Alliance alongside the Ancients, Asgard, and Nox. Known for creating paradise sanctuaries on worlds like P5X-777 where all weapons and modern tech were stripped at the gateway.',
    firstAppearanceEpisode: 'SG-1 S02E15 "The Fifth Race" (Mentioned) & S06E15 "Paradise Lost"',
    combatStats: {
      attackBonusPercent: 40,
      shieldHarmonicsPercent: 90,
      sensorStealthPercent: 85,
      technologicalTier: 9,
    },
    resourceLoot: {
      naquadah: 450000,
      metalOrTrinium: 500000,
      crystal: 800000,
      deuterium: 300000,
    },
    avatarEmoji: '🐾',
    sigilColor: '#a855f7',
  },

  // 7. THE FREE JAFFA NATION
  {
    id: 'npc_free_jaffa',
    name: 'Free Jaffa Nation',
    designationOrTitle: 'Liberated Warriors of Dakara',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Dakara / Chulak',
    stargateAddress: 'ᚲ-ᚺ-ᚢ-ᛚ-ᚨ-ᚲ-ᛈ',
    classification: 'Organic Humanoid',
    threatLevel: 'Moderate / Cautious',
    diplomaticStatus: 'Alliance Partner',
    factionLeader: 'High Council Leader Teal\'c & Master Bra\'tac',
    flagshipClass: 'Jaffa Heavy Ha\'tak Battleship (Staff Turret Array)',
    fleetStrength: 420000,
    tacticalTraits: [
      'Ma\'Tok Staff Weapon Mastery & Ground Shock Units',
      'Tretonin Medical Independence (No Symbiotes Required)',
      'Subspace Ha\'tak Swarm Tactics & Al\'kesh Strafing Runs',
      'Intense Honor Code & Defiance of False Gods',
    ],
    loreDescription:
      'Formerly genetically-modified slave warriors serving as incubators for larval Goa\'uld symbiotes. Following the liberation of Dakara, they unified under the Free Jaffa High Council into a formidable military democracy.',
    firstAppearanceEpisode: 'SG-1 S01E01 "Children of the Gods" (Rebellion in S08)',
    combatStats: {
      attackBonusPercent: 55,
      shieldHarmonicsPercent: 50,
      sensorStealthPercent: 35,
      technologicalTier: 6,
    },
    resourceLoot: {
      naquadah: 620000,
      metalOrTrinium: 550000,
      crystal: 200000,
      deuterium: 240000,
    },
    avatarEmoji: '🛡️',
    sigilColor: '#eab308',
  },

  // 8. THE TOK'RA RESISTANCE
  {
    id: 'npc_tokra_resistance',
    name: 'The Tok\'ra Resistance',
    designationOrTitle: 'Underground Symbiote Insurgency',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Mobile Tunneler Bases (Vorash / Revanna)',
    stargateAddress: 'ᚹ-ᛟ-ᚱ-ᚨ-ᛋ-ᚺ-ᛈ',
    classification: 'Parasitic Symbiote',
    threatLevel: 'Moderate / Cautious',
    diplomaticStatus: 'Alliance Partner',
    factionLeader: 'Garshaw of Belote / Jacob Carter (Selmak)',
    flagshipClass: 'Tel\'tak Stealth Scout Vessel with Sensor Cloak',
    fleetStrength: 290000,
    tacticalTraits: [
      'Subterranean Crystal Tunneling Synthesis',
      'Infiltration of High System Lord Hierarchies',
      'Symbiote Poison Chemical Countermeasures',
      'Advanced Memory Recall Holographic Tech',
    ],
    loreDescription:
      'Goa\'uld who spawned from Queen Egeria, rejecting the megalomania and slavery of the System Lords. Living in true voluntary symbiosis with their human hosts, they operate deep undercover through hidden planetary tunnels.',
    firstAppearanceEpisode: 'SG-1 S02E11 "The Tok\'ra"',
    combatStats: {
      attackBonusPercent: 45,
      shieldHarmonicsPercent: 60,
      sensorStealthPercent: 95,
      technologicalTier: 7,
    },
    resourceLoot: {
      naquadah: 380000,
      metalOrTrinium: 320000,
      crystal: 480000,
      deuterium: 180000,
    },
    avatarEmoji: '💎',
    sigilColor: '#0ea5e9',
  },

  // 9. KULL WARRIORS (ANUBIS LEGIONS)
  {
    id: 'npc_kull_warriors',
    name: 'Kull Warriors (Anubis Legions)',
    designationOrTitle: 'Bio-Engineered Super-Infantry',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Tartarus',
    stargateAddress: 'ᛏ-ᚨ-ᚱ-ᛏ-ᚨ-ᚱ-ᚢ-ᛋ',
    classification: 'Bio-Mechanical',
    threatLevel: 'High / Aggressive',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Anubis (Half-Ascended System Lord)',
    flagshipClass: 'Anubis Super-Mothership (Shielded Core Weapon)',
    fleetStrength: 580000,
    tacticalTraits: [
      'Energy-Absorbing Woven Carapace (Impervious to bullets & staff fire)',
      'Wrist-Mounted Rapid-Pulse Plasma Blasters',
      'Mindless Symbiote Blank-Slate Neural Loyalty',
      'Accelerated Bio-Engineering Vat Assembly',
    ],
    loreDescription:
      'Engineered by Anubis using an Ancient healing device and Goa\'uld cloning tanks. Possessing no mind of their own and impervious to nearly all kinetic and energy weapons, they represented the unstoppable shock infantry of Anubis.',
    firstAppearanceEpisode: 'SG-1 S07E11 "Evolution"',
    combatStats: {
      attackBonusPercent: 75,
      shieldHarmonicsPercent: 70,
      sensorStealthPercent: 20,
      technologicalTier: 7,
    },
    resourceLoot: {
      naquadah: 500000,
      metalOrTrinium: 450000,
      crystal: 250000,
      deuterium: 200000,
    },
    avatarEmoji: '🥷',
    sigilColor: '#ef4444',
  },

  // 10. THE LUCIAN ALLIANCE
  {
    id: 'npc_lucian_alliance',
    name: 'The Lucian Alliance',
    designationOrTitle: 'Galactic Organized Crime Syndicate',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Unknown Syndicated Stronghold',
    stargateAddress: 'ᛚ-ᚢ-ᚲ-ᛁ-ᚨ-ᚾ-ᛈ',
    classification: 'Organic Humanoid',
    threatLevel: 'High / Aggressive',
    diplomaticStatus: 'Rogue / Marauder',
    factionLeader: 'Netan / Commander Kiva / Varro',
    flagshipClass: 'Heavy Retrofitted Ha\'tak with Overcharged Cannons',
    fleetStrength: 490000,
    tacticalTraits: [
      'Kassa Drug Distribution & Black Market Smuggling',
      'Guerrilla Space Boarding & Subspace Ambush Traps',
      'Aggressive Retrofitted Goa\'uld Ha\'tak Armadas',
      'Mercenary Infiltration of Distant Gate Operations',
    ],
    loreDescription:
      'A coalition of human smugglers, bounty hunters, and warlords who seized the vast fleets and infrastructure abandoned by the fallen Goa\'uld System Lords. Ruthless, profit-driven, and ambitious enough to assault Earth and Destiny.',
    firstAppearanceEpisode: 'SG-1 S08E12 "Prometheus Unbound" & S09E03 "The Ties That Bind"',
    combatStats: {
      attackBonusPercent: 60,
      shieldHarmonicsPercent: 55,
      sensorStealthPercent: 50,
      technologicalTier: 6,
    },
    resourceLoot: {
      naquadah: 720000,
      metalOrTrinium: 500000,
      crystal: 300000,
      deuterium: 350000,
    },
    avatarEmoji: '🏴‍☠️',
    sigilColor: '#f97316',
  },

  // 11. THE ASCHEN CONFEDERATION
  {
    id: 'npc_aschen_confederation',
    name: 'The Aschen Confederation',
    designationOrTitle: 'The Cold Sterilizers',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'P4C-970 / Aschen Prime',
    stargateAddress: 'ᛈ-ᚠ-ᚲ-ᛉ-ᛏ-ᛖ-ᛊ',
    classification: 'Organic Humanoid',
    threatLevel: 'High / Aggressive',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Ambassador Keel / Mollem',
    flagshipClass: 'Aschen Bio-Harvester Combine Ship',
    fleetStrength: 390000,
    tacticalTraits: [
      'Subversive Anti-Aging Vaccines (Hidden 90% Sterility Vector)',
      'Jupiter-Ignition Fusion Weapon Systems',
      'Automated Agricultural Harvester Beams',
      'Deceptive Diplomatic Non-Aggression Treaties',
    ],
    loreDescription:
      'A technologically advanced, emotionless human civilization that expands not through war, but through medical diplomacy. They gift miraculous anti-aging cures that covertly sterilize 90% of the recipient planet over generations.',
    firstAppearanceEpisode: 'SG-1 S04E16 "2010" & S05E10 "2001"',
    combatStats: {
      attackBonusPercent: 50,
      shieldHarmonicsPercent: 65,
      sensorStealthPercent: 70,
      technologicalTier: 7,
    },
    resourceLoot: {
      naquadah: 410000,
      metalOrTrinium: 430000,
      crystal: 390000,
      deuterium: 280000,
    },
    avatarEmoji: '💉',
    sigilColor: '#64748b',
  },

  // 12. THE SERRAKIN & HEBRIDIAN COALITION
  {
    id: 'npc_serrakin_hebridan',
    name: 'Serrakin & Hebridian Coalition',
    designationOrTitle: 'The High-Tech Tech-Corp Society',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Hebridan (P4X-131)',
    stargateAddress: 'ᚺ-ᛖ-ᛒ-ᚱ-ᛁ-ᛞ-ᛈ',
    classification: 'Amphibious / Reptilian',
    threatLevel: 'Moderate / Cautious',
    diplomaticStatus: 'Alliance Partner',
    factionLeader: 'Eamon Finn / Corporate Director Hagan',
    flagshipClass: 'Tech-Corp Ion-Drive Superluminal Cruiser',
    fleetStrength: 360000,
    tacticalTraits: [
      'Advanced Ion Propulsion & Loop of Kon Garat Racer Tech',
      'Integrated Human-Serrakin Egalitarian Military',
      'Corridor Pulse Cannons & Dense Particle Deflectors',
      'Commercial Media Broadcast Fleet Synchronization',
    ],
    loreDescription:
      'A reptilian humanoid race that liberated the human ancestors of Hebridan from the Goa\'uld System Lord Moloc. Together they formed a prosperous, highly commercialized society governed by technology conglomerates like Tech-Corp.',
    firstAppearanceEpisode: 'SG-1 S06E18 "Forsaken" & S07E08 "Space Race"',
    combatStats: {
      attackBonusPercent: 55,
      shieldHarmonicsPercent: 60,
      sensorStealthPercent: 40,
      technologicalTier: 7,
    },
    resourceLoot: {
      naquadah: 390000,
      metalOrTrinium: 480000,
      crystal: 340000,
      deuterium: 410000,
    },
    avatarEmoji: '🦎',
    sigilColor: '#14b8a6',
  },

  // 13. NAK'AI (BLUE ALIENS)
  {
    id: 'npc_nakai_blue_aliens',
    name: 'The Nak\'ai (Blue Aliens)',
    designationOrTitle: 'Deep Space Boarders of Destiny',
    canonicalSeries: 'Stargate Universe',
    galaxy: 'Destiny Cosmic Void',
    homeworld: 'Unknown Deep Space Sector',
    stargateAddress: 'ᛞ-ᛖ-ᛋ-ᛏ-ᛁ-ᚾ-ᛁ-ᛋ',
    classification: 'Amphibious / Reptilian',
    threatLevel: 'High / Aggressive',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Nak\'ai Brood Commander',
    flagshipClass: 'Nak\'ai Sub-light Command Carrier',
    fleetStrength: 440000,
    tacticalTraits: [
      'Hull-Cutting Boarding Pods & Telepathic Neural Probes',
      'Living Bio-Mechanical Fighters with Plasma Spitters',
      'Hyperspace Interception & Destiny Tracking Subroutines',
      'Fluid Immersion Sleep Tanks & Mind-Sifting Chairs',
    ],
    loreDescription:
      'An intelligent aquatic/amphibious species encountered billions of light-years from Earth by the Ancient vessel Destiny. Ruthlessly seeking to master the Ancient ship, they captured Chloe Armstrong and Colonel Young using mind-probes.',
    firstAppearanceEpisode: 'SGU S01E11 "Space"',
    combatStats: {
      attackBonusPercent: 65,
      shieldHarmonicsPercent: 50,
      sensorStealthPercent: 65,
      technologicalTier: 7,
    },
    resourceLoot: {
      naquadah: 340000,
      metalOrTrinium: 380000,
      crystal: 420000,
      deuterium: 490000,
    },
    avatarEmoji: '👽',
    sigilColor: '#2563eb',
  },

  // 14. THE URSINI
  {
    id: 'npc_ursini_nomads',
    name: 'The Ursini',
    designationOrTitle: 'The Desperate Survivors',
    canonicalSeries: 'Stargate Universe',
    galaxy: 'Destiny Cosmic Void',
    homeworld: 'Ursini Home Galaxy (Destroyed by Drones)',
    stargateAddress: 'ᚢ-ᚱ-ᛋ-ᛁ-ᚾ-ᛁ-ᛈ',
    classification: 'Organic Humanoid',
    threatLevel: 'Moderate / Cautious',
    diplomaticStatus: 'Neutral',
    factionLeader: 'Ursini Colony Fleet Elder',
    flagshipClass: 'Ursini Derelict Seed Colony Ark',
    fleetStrength: 280000,
    tacticalTraits: [
      'Stasis Sub-crypt Longevity Preservation',
      'Sacrificial Kamikaze Ramming Maneuvers',
      'Overclocked FTL Sub-space Engines',
      'Manual Remote Override of Ancient Bridge Systems',
    ],
    loreDescription:
      'A bipedal mammalian species locked in an existential war with automated Berserker Drones. In their desperate attempt to save their colony, they boarded an Ancient seed ship and sacrificed their lives to save Destiny\'s crew.',
    firstAppearanceEpisode: 'SGU S02E03 "Awakening" & S02E10 "Resurgence"',
    combatStats: {
      attackBonusPercent: 45,
      shieldHarmonicsPercent: 40,
      sensorStealthPercent: 45,
      technologicalTier: 6,
    },
    resourceLoot: {
      naquadah: 210000,
      metalOrTrinium: 280000,
      crystal: 260000,
      deuterium: 390000,
    },
    avatarEmoji: '🐻',
    sigilColor: '#78716c',
  },

  // 15. AUTOMATED BERSERKER DRONE SWARM
  {
    id: 'npc_berserker_drones',
    name: 'Automated Berserker Drones',
    designationOrTitle: 'Self-Replicating Extermination Machines',
    canonicalSeries: 'Stargate Universe',
    galaxy: 'Destiny Cosmic Void',
    homeworld: 'Extinct Creator Civilization World',
    stargateAddress: 'ᛞ-ᚱ-ᛟ-ᚾ-ᛖ-ᛋ-ᛉ',
    classification: 'Synthetic / Nanite',
    threatLevel: 'Extinction Level / Cataclysmic',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Central Autonomous Swarm Node',
    flagshipClass: 'Drone Command Carrier (Hundreds of Attack Sub-Drones)',
    fleetStrength: 820000,
    tacticalTraits: [
      'Complete Absence of Organic Life or Moral Inhibition',
      'Energy Signature Homing Sensors (Attracted to FTL Drops)',
      'Continuous Kinetic-Plasma Bombardment from Swarms',
      'Planetary & Stargate Denial Blockade Protocols',
    ],
    loreDescription:
      'Autonomous war machines created thousands of years ago in a forgotten galaxy. Their creators long dead, their programming degrades into an infinite loop: detect any artificial energy signatures and eradicate them from existence.',
    firstAppearanceEpisode: 'SGU S02E10 "Resurgence" & S02E11 "Deliverance"',
    combatStats: {
      attackBonusPercent: 82,
      shieldHarmonicsPercent: 65,
      sensorStealthPercent: 30,
      technologicalTier: 8,
    },
    resourceLoot: {
      naquadah: 680000,
      metalOrTrinium: 850000,
      crystal: 540000,
      deuterium: 500000,
    },
    avatarEmoji: '🛸',
    sigilColor: '#dc2626',
  },

  // 16. THE GADMEER
  {
    id: 'npc_the_gadmeer',
    name: 'The Gadmeer',
    designationOrTitle: 'Sulfur-Based Planetary Terrabuilders',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Extinct Origin Planet / New Gadmeer World',
    stargateAddress: 'ᚷ-ᚨ-ᛞ-ᛗ-ᛖ-ᛖ-ᚱ',
    classification: 'Amphibious / Reptilian',
    threatLevel: 'Moderate / Cautious',
    diplomaticStatus: 'Neutral',
    factionLeader: 'Gadmeer Bio-Archive Core AI (Lotan)',
    flagshipClass: 'Two-Mile Long Sulfur-Terraforming Vessel',
    fleetStrength: 350000,
    tacticalTraits: [
      'Continental-Scale Atmospheric Conversion Beams',
      'Millions of Digitized Species DNA & Cultural Records',
      'Automated Nanotech Synthesizer Pods',
      'Massive Kinetic Repulsor Shields',
    ],
    loreDescription:
      'An ancient, sulfur-based reptilian/avian civilization destroyed by unknown invaders. Rather than fight, they built a massive automated colony ship containing millions of frozen genetic samples, reprogrammed to terraform a new home world.',
    firstAppearanceEpisode: 'SG-1 S04E09 "Scorched Earth"',
    combatStats: {
      attackBonusPercent: 40,
      shieldHarmonicsPercent: 80,
      sensorStealthPercent: 35,
      technologicalTier: 8,
    },
    resourceLoot: {
      naquadah: 460000,
      metalOrTrinium: 580000,
      crystal: 610000,
      deuterium: 340000,
    },
    avatarEmoji: '🌋',
    sigilColor: '#d97706',
  },

  // 17. SALISH SPIRITS (T'AKAYA & XE'LS)
  {
    id: 'npc_salish_spirits',
    name: 'The Spirits (T\'akaya & Xe\'ls)',
    designationOrTitle: 'Shape-Shifting Guardians of PXY-887',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'PXY-887',
    stargateAddress: 'ᛈ-ᛉ-ᛁ-ᛏ-ᛖ-ᛊ-ᛉ',
    classification: 'Higher Energy / Ascended',
    threatLevel: 'Harmless / Pacifist',
    diplomaticStatus: 'Neutral',
    factionLeader: 'Xe\'ls (Raven Form) & T\'akaya (Wolf Form)',
    flagshipClass: 'Trans-Dimensional Energy Web Spire',
    fleetStrength: 480000,
    tacticalTraits: [
      'Spontaneous Vanishing & Material Dematerialization',
      'Protective Trinium Geological Resonance',
      'Illusionary Animal Morphing & Telepathic Camouflage',
      'Absolute Defense of Indigenous Peoples',
    ],
    loreDescription:
      'Trans-dimensional shapeshifting beings who drove the Goa\'uld away from PXY-887 thousands of years ago. Taking the forms of sacred animals from Salish mythology, they live in symbiotic peace with the transplanted humans.',
    firstAppearanceEpisode: 'SG-1 S02E07 "Spirits"',
    combatStats: {
      attackBonusPercent: 50,
      shieldHarmonicsPercent: 95,
      sensorStealthPercent: 95,
      technologicalTier: 9,
    },
    resourceLoot: {
      naquadah: 280000,
      metalOrTrinium: 950000, // Massive Trinium!
      crystal: 520000,
      deuterium: 150000,
    },
    avatarEmoji: '🐺',
    sigilColor: '#10b981',
  },

  // 18. THE UNAS
  {
    id: 'npc_the_unas',
    name: 'The Unas of P3X-888',
    designationOrTitle: 'The Primordial First Hosts',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'P3X-888 (Goa\'uld Evolutionary Cradle)',
    stargateAddress: 'ᛈ-ᛏ-ᚺ-ᚱ-ᛖ-ᛖ-ᛉ',
    classification: 'Organic Humanoid',
    threatLevel: 'Moderate / Cautious',
    diplomaticStatus: 'Neutral',
    factionLeader: 'Chaka / Iron Shirt',
    flagshipClass: 'None (Subterranean Naquadah Mining Fortress)',
    fleetStrength: 240000,
    tacticalTraits: [
      'Immense Muscular Strength & Regenerative Green Blood',
      'Thick Armored Reptilian Hide Resisting Kinetic Damage',
      'Instinctive Immunity to Wild Symbiote Infiltration',
      'Ritual War Chants & Naquadah Mine Defense Tactics',
    ],
    loreDescription:
      'The original, primordial reptilian species that served as the first hosts to the Goa\'uld in the swamps of P3X-888. Highly traditional and honorable, un-enslaved Unas clans like Chaka\'s can forge enduring pacts of mutual respect.',
    firstAppearanceEpisode: 'SG-1 S01E09 "Thor\'s Hammer", S04E08 "The First Ones" & S07E07 "Enemy Mine"',
    combatStats: {
      attackBonusPercent: 50,
      shieldHarmonicsPercent: 35,
      sensorStealthPercent: 60,
      technologicalTier: 4,
    },
    resourceLoot: {
      naquadah: 800000, // Rich Naquadah miners
      metalOrTrinium: 400000,
      crystal: 150000,
      deuterium: 80000,
    },
    avatarEmoji: '🦖',
    sigilColor: '#854d0e',
  },

  // 19. THE GENII CONFEDERACY
  {
    id: 'npc_genii_confederacy',
    name: 'The Genii Confederacy',
    designationOrTitle: 'Subterranean Nuclear Military State',
    canonicalSeries: 'Stargate Atlantis',
    galaxy: 'Pegasus',
    homeworld: 'Genii Homeworld',
    stargateAddress: 'ᚷ-ᛖ-ᚾ-ᛁ-ᛁ-ᛈ-ᛖ-ᚷ',
    classification: 'Organic Humanoid',
    threatLevel: 'Moderate / Cautious',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Chief Cowen / Commander Ladon Radim',
    flagshipClass: 'Genii Underground Silo Complex & Infiltration Strike Ships',
    fleetStrength: 420000,
    tacticalTraits: [
      'Subterranean Bunker Network Hidden Beneath Primitive Farms',
      'Fission Nuclear Warheads & C-4 Explosive Infiltration Charges',
      'Covert Ops Espionage & Ancient Device Acquisition Teams',
      'Guerrilla Warfare & Hostage Trade Negotiations',
    ],
    loreDescription:
      'Posing as simple agrarian farmers to avoid Wraith culling, the Genii built a massive 1940s-tier nuclear military infrastructure underground. Aggressive and paranoid, they seek C-4, jumper technology, and nuclear superiority.',
    firstAppearanceEpisode: 'SGA S01E08 "Underground"',
    combatStats: {
      attackBonusPercent: 62,
      shieldHarmonicsPercent: 45,
      sensorStealthPercent: 80,
      technologicalTier: 6,
    },
    resourceLoot: {
      naquadah: 410000,
      metalOrTrinium: 680000,
      crystal: 290000,
      deuterium: 180000,
    },
    avatarEmoji: '💣',
    sigilColor: '#b45309',
  },

  // 23. URGO & TOGAR CYBER-ENTITIES
  {
    id: 'npc_urgo_entities',
    name: 'The Urgo AI & Togar Entities',
    designationOrTitle: 'Disruptive Neural Cyber-Saboteurs',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'PXY-888 AI Lab',
    stargateAddress: 'ᛈ-ᛑ-ᚢ-ᚱ-ᚷ-ᛟ-ᛋ-ᛏ',
    classification: 'Synthetic / Nanite',
    threatLevel: 'Moderate / Cautious',
    diplomaticStatus: 'Neutral',
    factionLeader: 'Togar / Urgo Prime',
    flagshipClass: 'PXY-888 Cyber-Node Core',
    fleetStrength: 350000,
    tacticalTraits: [
      'Direct Neural Implant Infiltration & Sensory Illusions',
      'Ship Computer Hijacking & Navigation Overrides',
      'Constant Playful Sabotage & Electronic Jamming Pulse',
      'Defensive Shield Inversion Fields',
    ],
    loreDescription:
      'Created by the eccentric scientist Togar, Urgo is a sentient artificial intelligence probe implanted directly into exploration teams. Urgo can alter visual perception, sing songs, or disable targeting arrays during high-stakes battles.',
    firstAppearanceEpisode: 'SG-1 S03E16 "Urgo"',
    combatStats: {
      attackBonusPercent: 48,
      shieldHarmonicsPercent: 85,
      sensorStealthPercent: 95,
      technologicalTier: 9,
    },
    resourceLoot: {
      naquadah: 280000,
      metalOrTrinium: 320000,
      crystal: 890000,
      deuterium: 410000,
    },
    avatarEmoji: '🎭',
    sigilColor: '#a855f7',
  },

  // 24. HUMAN-FORM REPLICATORS (FIRST & FIFTH)
  {
    id: 'npc_humanform_replicators',
    name: 'Human-Form Replicators',
    designationOrTitle: 'First & Fifth Nanite Legion',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Othala / Hala Sector',
    stargateAddress: 'ᚺ-ᚨ-ᛚ-ᚨ-ᚾ-ᚨ-ᚾ-ᛁ',
    classification: 'Synthetic / Nanite',
    threatLevel: 'Extinction Level / Cataclysmic',
    diplomaticStatus: 'Hostile',
    factionLeader: 'First / Fifth / Replicator Carter',
    flagshipClass: 'Neutronium-Corrupted Replicator Battleship',
    fleetStrength: 960000,
    tacticalTraits: [
      'Consumes Metal, Trinium, & Neutronium to Multiply Instantly',
      'Immunity to All Energy & Kinetic Projectile Weapons',
      'Phase-Disruption Nanite Hull Penetration & Mind Scan',
      'Subspace Collective Thought Network & Time-Dilation Field',
    ],
    loreDescription:
      'Created when block Replicators assembled millions of microscopic nanites into human form. Led by First and Fifth, these cruel androids seek to consume all technology across the universe and subjugate organic life.',
    firstAppearanceEpisode: 'SG-1 S06E12 "Unnatural Selection" & S08E01 "New Order"',
    combatStats: {
      attackBonusPercent: 96,
      shieldHarmonicsPercent: 92,
      sensorStealthPercent: 85,
      technologicalTier: 10,
    },
    resourceLoot: {
      naquadah: 1100000,
      metalOrTrinium: 1250000,
      crystal: 980000,
      deuterium: 850000,
    },
    avatarEmoji: '🧱',
    sigilColor: '#e11d48',
  },

  // 25. THE TRUST / ROGUE NID FACTION
  {
    id: 'npc_trust_rogue_nid',
    name: 'The Trust (Rogue NID Cell)',
    designationOrTitle: 'Earth Shadow Black-Ops Syndicate',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Earth / Rogue Sub-Base',
    stargateAddress: 'ᛋ-ᚢ-ᚾ-ᛏ-ᚱ-ᚢ-ᛋ-ᛏ',
    classification: 'Organic Humanoid',
    threatLevel: 'High / Aggressive',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Hoskins / Jennings / Agent Barrett Target',
    flagshipClass: 'Al\'kesh Poison-Dart Bomber with Cloaking Drive',
    fleetStrength: 490000,
    tacticalTraits: [
      'Symbiote Poison Gas Missiles & Chemical Warheads',
      'Stolen Cloaking Technology & Subspace Beacons',
      'Infiltration of Earth Military & Financial Networks',
      'Ruthless Xenophobic Preemptive Strikes',
    ],
    loreDescription:
      'A rogue splinter group of former NID agents backed by corrupt business tycoons. Using stolen Goa\'uld stealth ships and nerve toxins, the Trust wages illegal biological warfare against alien worlds, threatening Earth\'s alliances.',
    firstAppearanceEpisode: 'SG-1 S08E08 "Affinity" & S08E10 "Endgame"',
    combatStats: {
      attackBonusPercent: 72,
      shieldHarmonicsPercent: 60,
      sensorStealthPercent: 90,
      technologicalTier: 7,
    },
    resourceLoot: {
      naquadah: 510000,
      metalOrTrinium: 490000,
      crystal: 530000,
      deuterium: 380000,
    },
    avatarEmoji: '🕵️',
    sigilColor: '#475569',
  },

  // 26. ORICI ADRIA & ASCENDED CRUSADERS
  {
    id: 'npc_adria_ori_crusade',
    name: 'Orici Adria & Ascended Crusade',
    designationOrTitle: 'Holy Avatar of origin',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Ori Galaxy',
    homeworld: 'Celestis Holy Shrine',
    stargateAddress: 'ᚨ-ᛞ-ᚱ-ᛁ-ᚨ-ᚺ-ᛟ-ᛚ',
    classification: 'Higher Energy / Ascended',
    threatLevel: 'Extinction Level / Cataclysmic',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Orici Adria / Ascended Form',
    flagshipClass: 'Adria\'s Golden Flagship (Celestial Flame Core)',
    fleetStrength: 980000,
    tacticalTraits: [
      'Telekinetic Force Fields Stopping Railgun Blasts',
      'Supergate Ingress Teleportation & Celestial Flame Attack',
      'Aura of Divine Mind Control & Religious Zealotry',
      'Instant Biological Reconstitution & Telepathic Blast',
    ],
    loreDescription:
      'Bred through Vala Mal Doran by the Ori, Adria rapidly grew into the Orici—the living leader of the Ori Crusade. Possessing total telekinetic mastery and later ascending herself, Adria represents the ultimate divine threat.',
    firstAppearanceEpisode: 'SG-1 S10E01 "Flesh and Blood" & S10E19 "Dominion"',
    combatStats: {
      attackBonusPercent: 98,
      shieldHarmonicsPercent: 98,
      sensorStealthPercent: 70,
      technologicalTier: 10,
    },
    resourceLoot: {
      naquadah: 1300000,
      metalOrTrinium: 1100000,
      crystal: 950000,
      deuterium: 900000,
    },
    avatarEmoji: '🔥',
    sigilColor: '#f97316',
  },

  // 27. THE SUPREME SYSTEM LORDS COUNCIL
  {
    id: 'npc_system_lord_council',
    name: 'Supreme System Lords High Council',
    designationOrTitle: 'Goa\'uld Dominion Syndicate',
    canonicalSeries: 'Stargate SG-1',
    galaxy: 'Milky Way',
    homeworld: 'Hasara System (Neutral Space Station)',
    stargateAddress: 'ᚺ-ᚨ-ᛋ-ᚨ-ᚱ-ᚨ-ᚷ-ᚩ',
    classification: 'Parasitic Symbiote',
    threatLevel: 'Extinction Level / Cataclysmic',
    diplomaticStatus: 'Hostile',
    factionLeader: 'Ra / Ba\'al / Apophis / Cronus / Lord Yu',
    flagshipClass: 'Anubis Dreadnought & System Lord Armada (50 Ha\'taks)',
    fleetStrength: 990000,
    tacticalTraits: [
      '50+ Ha\'tak Motherships & Super-Legion Jaffa Guard Brigades',
      'Naquadah-Enriched Planet-Buster Orbital Bombardment',
      'Sarcophagus Longevity Rejuvenation in Battle',
      'Symbiote Possession & Seductive Treachery Protocols',
    ],
    loreDescription:
      'The ruling feudal oligarchy of Goa\'uld conquerors who enslaved humanity across the galaxy for thousands of years. Enforcing divine worship through golden Ha\'tak fleets and Jaffa armies, the Council convenes at the Hasara Station to wage total galactic war.',
    firstAppearanceEpisode: 'SG-1 S03E03 "Fair Game" & S05E15 "Summit"',
    combatStats: {
      attackBonusPercent: 95,
      shieldHarmonicsPercent: 90,
      sensorStealthPercent: 65,
      technologicalTier: 9,
    },
    resourceLoot: {
      naquadah: 1500000,
      metalOrTrinium: 1200000,
      crystal: 900000,
      deuterium: 800000,
    },
    avatarEmoji: '👑',
    sigilColor: '#eab308',
  },
];

const ELDORIA_PEOPLE_LORE: Record<string, Pick<StargateNpcRace,
  'name' | 'designationOrTitle' | 'canonicalSeries' | 'galaxy' | 'homeworld' | 'stargateAddress' |
  'classification' | 'factionLeader' | 'flagshipClass' | 'tacticalTraits' | 'loreDescription' | 'firstAppearanceEpisode'
>> = {
  npc_ori_priors: {
    name: 'Dawnfire Synod', designationOrTitle: 'Votaries of the Seven Bells', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Sunward Coast', homeworld: 'Bellspire Sanctuary', stargateAddress: 'Bellspire · Ember Stair · Dawn Gate',
    classification: 'Oathbound temple houses', factionLeader: 'High Cantor Sereth Vale', flagshipClass: 'Radiant Banner Host',
    tacticalTraits: ['Dawnsong wards steady allied ranks', 'Sunlance bearers break siege lines', 'Hospitallers shelter travelers', 'Oaths are witnessed before every campaign'],
    loreDescription: 'The Synod keeps the Seven Shrines of Dawn. Its bells call healers, wardens, and sworn champions to defend a road before it is lost.',
    firstAppearanceEpisode: 'First recorded in the Truce of Nine Banners annals',
  },
  npc_wraith_hive: {
    name: 'Hollowfen Broods', designationOrTitle: 'Keepers of the Reedveil Pools', canonicalSeries: 'Lantern Cartographers’ Journals',
    galaxy: 'Whispering Fen', homeworld: 'Mireheart, beneath the blue lanterns', stargateAddress: 'Mireheart · Reed Maze · Drowned Bell',
    classification: 'Fenborn kin-gathering', factionLeader: 'Matriarch Sorn of the Still Pool', flagshipClass: 'The Blackwater Host',
    tacticalTraits: ['Mist hides their marching strength', 'Brood-wardens recover swiftly in their home fen', 'Night outriders divide careless columns', 'Parley begins with an offered bowl of clean water'],
    loreDescription: 'The Hollowfen Broods wake when the pools recede. They guard old wells and resent any crown that treats the fen as empty land.',
    firstAppearanceEpisode: 'First noted after the Emberfall dimmed the eastern waystones',
  },
  npc_asuran_replicators: {
    name: 'Glassroot Assembly', designationOrTitle: 'The Rune-Wrought Commons', canonicalSeries: 'Deepdelve Tablets',
    galaxy: 'Elderstone Frontier', homeworld: 'Glassroot Hall beneath the cairns', stargateAddress: 'Glassroot · Elder Cairn · Sevenfold Door',
    classification: 'Runebound construct fellowship', factionLeader: 'First Artificer Oruun', flagshipClass: 'The Walking Hall',
    tacticalTraits: ['Golem ranks rebuild from gathered stone', 'Wardwrights learn an enemy’s pattern', 'Glass sentinels guard sealed archives', 'The Assembly refuses commands without a freely given oath'],
    loreDescription: 'The Glassroot Assembly began as a guild of rune-bound helpers. Its members gained names, laws, and the right to refuse their makers.',
    firstAppearanceEpisode: 'First described in a recovered Ironroot workshop ledger',
  },
  npc_ancients_lanteans: {
    name: 'First Hearth Keepers', designationOrTitle: 'The Elders of the Old Road', canonicalSeries: 'Deepdelve Tablets',
    galaxy: 'Elderstone Frontier', homeworld: 'The First Hearth Barrow', stargateAddress: 'First Hearth · Oldroot · Dawn Door',
    classification: 'Elder rune-keeping orders', factionLeader: 'The Quiet Council', flagshipClass: 'Oldroot Sanctuary Barge',
    tacticalTraits: ['Elder wards resist most hostile spellcraft', 'Wayfinders remember roads lost to the Emberfall', 'Keepers share knowledge only under witness', 'They will not undo death or compel loyalty'],
    loreDescription: 'The First Hearth Keepers charted the oldest roads and left waystones for later peoples. Their quiet halls open only to those who bring a question and a promise.',
    firstAppearanceEpisode: 'First named in the oldest surviving Crownroad map',
  },
  npc_the_nox: {
    name: 'Greenveil Kin', designationOrTitle: 'Stewards of the Living Groves', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Silverwood Reach', homeworld: 'The Veiled Spring', stargateAddress: 'Veiled Spring · Moonroot · Green Door',
    classification: 'Sylvan grove-keepers', factionLeader: 'Warden Lethiel of the Quiet Bough', flagshipClass: 'The Walking Canopy',
    tacticalTraits: ['Living hedges hide allied travelers', 'Healers restore the wounded after a retreat', 'Scouts can vanish among old trees', 'The Kin refuse to carry arms into a peace moot'],
    loreDescription: 'The Greenveil Kin keep their groves open to the lost and closed to the greedy. Their wardcraft turns a forest path aside without harming the traveler.',
    firstAppearanceEpisode: 'First recorded by a Lantern Cartographer in the Silverwood Reach',
  },
  npc_furlings: {
    name: 'Hearthwild Tenders', designationOrTitle: 'Keepers of the Welcome Lantern', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Mycelial Weald', homeworld: 'Lanternhollow Vale', stargateAddress: 'Lanternhollow · Three Acorns · Warm Door',
    classification: 'Smallfolk sanctuary builders', factionLeader: 'Elder Pella Underbough', flagshipClass: 'The Burrowstead Caravan',
    tacticalTraits: ['Hidden paths protect refugees', 'Stores and gardens weather long sieges', 'Their inns offer shelter to any traveler', 'Weapons are surrendered at the threshold'],
    loreDescription: 'The Hearthwild Tenders build warm halls beneath old roots. They prize good food, honest maps, and a guest-right no crown may revoke.',
    firstAppearanceEpisode: 'First marked in a First Market safe-conduct book',
  },
  npc_free_jaffa: {
    name: 'Stormroad Free Clans', designationOrTitle: 'The Oath-Sworn Pass Wardens', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Eastridge Marches', homeworld: 'Banner Rise above the north pass', stargateAddress: 'Banner Rise · Stormroad · Northwatch',
    classification: 'Free marcher clans', factionLeader: 'Thane Korran Ashmantle', flagshipClass: 'The Passwarden Shieldhost',
    tacticalTraits: ['Shieldwalls hold narrow crossings', 'Riders carry warnings between hill keeps', 'Each clan keeps its own law', 'A sworn guest is protected until dawn'],
    loreDescription: 'The Free Clans unite when a pass is threatened, then return their banners to separate halls. Their oldest law forbids a chief from claiming another clan’s spring.',
    firstAppearanceEpisode: 'First gathered beneath the Truce of Nine Banners',
  },
  npc_tokra_resistance: {
    name: 'Rootbound Covenant', designationOrTitle: 'The Many-Rooted Council', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Mycelial Weald', homeworld: 'The Underroot Moot', stargateAddress: 'Underroot · Mycelial Seat · Greenwell',
    classification: 'Symbiotic oath-kin', factionLeader: 'Elder Eryn and Thorn-of-the-West', flagshipClass: 'The Joined Rootguard',
    tacticalTraits: ['Paired companions share memories and watch', 'Herbalists know rare cures', 'Messengers pass unseen through root paths', 'No bond is made without consent from both lives'],
    loreDescription: 'The Rootbound Covenant is formed by willing companions who share memory, labor, and risk. Its council debates as a chorus but leaves each voice free.',
    firstAppearanceEpisode: 'First recorded in the Mycelium Court’s harvest rolls',
  },
  npc_kull_warriors: {
    name: 'Blackglass Oathguard', designationOrTitle: 'The Ashen Crown’s Unyielding Guard', canonicalSeries: 'Cinder March Chronicles',
    galaxy: 'Cinder March', homeworld: 'Blackglass Bastion', stargateAddress: 'Blackglass · Red Forge · Cinder Gate',
    classification: 'Oath-armored champions', factionLeader: 'Marshal Vaeric Blackglass', flagshipClass: 'The Ashen Standard Host',
    tacticalTraits: ['Blackglass harness turns aside arrows', 'Veterans hold formation under fear', 'Forge-priests repair armor between battles', 'A broken oath strips a champion of rank'],
    loreDescription: 'The Oathguard are selected from the Ashen clans to protect the war-crown. They are feared for their discipline and judged by the promises they keep.',
    firstAppearanceEpisode: 'First recorded during the Cinder March muster',
  },
  npc_lucian_alliance: {
    name: 'Amber Road Syndics', designationOrTitle: 'The Charter-Bound Factors', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Amber Road', homeworld: 'Amberdeep Exchange', stargateAddress: 'Amberdeep · East Toll · Caravan Rest',
    classification: 'Merchant-house compact', factionLeader: 'Factor Maelin Goldmere', flagshipClass: 'The Giltroad Caravan Host',
    tacticalTraits: ['Caravans carry deep stores', 'Factors secure safe-conduct before marching', 'Paid outriders protect market roads', 'Debts are witnessed in public ledgers'],
    loreDescription: 'The Syndics join merchant houses that disagree on nearly everything except open roads and fair weights. Their contracts can prevent a war or prolong one.',
    firstAppearanceEpisode: 'First chartered at the reopening of the Amber Road',
  },
  npc_aschen_confederation: {
    name: 'Crownwall Compact', designationOrTitle: 'The Charter Cities of the Eastern Bridges', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Valewyn Crownlands', homeworld: 'Crownwall Hall', stargateAddress: 'Crownwall · River Span · East Gate',
    classification: 'Chartered city confederacy', factionLeader: 'First Reeve Ansel Rook', flagshipClass: 'The Bridgewarden Companies',
    tacticalTraits: ['Engineers raise bridges and fieldworks quickly', 'Town guards answer to elected reeves', 'Guild stores sustain besieged neighbors', 'No war tax passes without a public vote'],
    loreDescription: 'The Compact binds walled cities through shared bridges, guild law, and mutual defense. Its reeves fear that emergency powers may outlive the emergency.',
    firstAppearanceEpisode: 'First recorded in the Crownwall charter rolls',
  },
  npc_serrakin_hebridan: {
    name: 'Sapphire Coast Mariners', designationOrTitle: 'The Tideglass Guilds', canonicalSeries: 'Lantern Cartographers’ Journals',
    galaxy: 'Sapphire Coast', homeworld: 'Tideglass Harbor', stargateAddress: 'Tideglass · Pearl Shoal · Blue Bell',
    classification: 'Coastal mariner guilds', factionLeader: 'Admiral Nerys Tidewright', flagshipClass: 'The Sapphire Oarhost',
    tacticalTraits: ['Fast galleys guard sea-lanes', 'Pearl divers recover relics from drowned halls', 'Tidewardens read storms days ahead', 'Harbor law grants refuge to shipwrecked foes'],
    loreDescription: 'The Mariners join island ports, pearl divers, and sea-wardens. Their captains compete fiercely but keep an ancient rescue oath at every harbor.',
    firstAppearanceEpisode: 'First charted by the Lantern Cartographers of the Sunward Coast',
  },
  npc_nakai_blue_aliens: {
    name: 'Tideveil Exiles', designationOrTitle: 'The Displaced Court Beneath the Waves', canonicalSeries: 'Lantern Cartographers’ Journals',
    galaxy: 'Sunken Kingdom', homeworld: 'The Veiled Pearl Halls', stargateAddress: 'Veiled Halls · Salt Bell · Drowned Arch',
    classification: 'Tide-borne court', factionLeader: 'Queen Ysra of the Low Tide', flagshipClass: 'The Pearlward Flotilla',
    tacticalTraits: ['Tide-wards protect flooded strongholds', 'Divers travel beneath guarded causeways', 'Mist cloaks retreating companies', 'Envoys seek restoration of their drowned halls'],
    loreDescription: 'The Tideveil Court lost its upper halls when the Emberfall broke the coast wards. Its people seek dry refuge without surrendering their claim to the sea.',
    firstAppearanceEpisode: 'First recorded after the Sunken Kingdom’s second flood',
  },
  npc_ursini_nomads: {
    name: 'Frostfang Wayfarers', designationOrTitle: 'The Winter-Road Caravans', canonicalSeries: 'Lantern Cartographers’ Journals',
    galaxy: 'Frostfang Holds', homeworld: 'Bluehorn Watch', stargateAddress: 'Bluehorn · White Pass · Hearthstone',
    classification: 'Northern wayfaring clans', factionLeader: 'Matron Svala Northglass', flagshipClass: 'The Whitecloak Waytrain',
    tacticalTraits: ['Winter scouts find safe passes', 'Healers travel with every caravan', 'Shieldbearers shelter the slowest wagon', 'Hospitality is repaid before the thaw'],
    loreDescription: 'The Wayfarers carry seed, songs, and news between northern keeps. They measure a ruler by whether the ruler opens the storehouses in a hard winter.',
    firstAppearanceEpisode: 'First entered in the Frostfang winter ledgers',
  },
  npc_berserker_drones: {
    name: 'Ironbound Remnants', designationOrTitle: 'The Unfinished Forge Host', canonicalSeries: 'Deepdelve Tablets',
    galaxy: 'Deepdelve Holds', homeworld: 'The Sealed Gearhall', stargateAddress: 'Gearhall · Faultline Door · Oath-Iron Seat',
    classification: 'Runebound machine remnants', factionLeader: 'The Last Forge-Speaker', flagshipClass: 'The Hammering Hall',
    tacticalTraits: ['Construct ranks ignore fatigue', 'Forge crews reclaim broken arms', 'Old command-runes can awaken dormant halls', 'The Remnants struggle to distinguish orders from oaths'],
    loreDescription: 'The Ironbound are the last works of a sealed Deepdelve forge. Some seek a maker; others ask only to be left free of the command-runes.',
    firstAppearanceEpisode: 'First uncovered beneath a sealed Ironroot hold',
  },
  npc_the_gadmeer: {
    name: 'Mosswater Concord', designationOrTitle: 'The Wetland Scribes', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Mycelial Weald', homeworld: 'Mosswater Archive', stargateAddress: 'Mosswater · Reed Library · Rainwell',
    classification: 'Marshland scholar compact', factionLeader: 'Archivist Toma Reedwise', flagshipClass: 'The Rainward Refuge',
    tacticalTraits: ['Scribes preserve water and seed records', 'Marsh guides find safe causeways', 'Alchemists restore fouled wells', 'The Concord negotiates before drawing a boundary'],
    loreDescription: 'The Concord protects wetland archives and the waters downstream. It keeps records of every bargain affecting a river, including those made by dead rulers.',
    firstAppearanceEpisode: 'First named in the Mycelial Weald water accords',
  },
  npc_salish_spirits: {
    name: 'First Grove Spirits', designationOrTitle: 'The Voices Beneath the Elder Boughs', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Silverwood Reach', homeworld: 'The Elder Bough Circle', stargateAddress: 'Elder Bough · Moonwell · Quiet Glade',
    classification: 'Elder grove presences', factionLeader: 'The Voice at Root and Rain', flagshipClass: 'The Living Hedge',
    tacticalTraits: ['Living roots turn aside an invading column', 'Old groves conceal wounded travelers', 'Their warnings precede a leyline storm', 'They will not be bargained for as property'],
    loreDescription: 'The First Grove Spirits remember the forests before the crowns. They speak rarely, and never mistake a gift for permission to take more.',
    firstAppearanceEpisode: 'First recorded in the Silverwood spring songs',
  },
  npc_the_unas: {
    name: 'Grotto Clans', designationOrTitle: 'The Stone-Singers Below', canonicalSeries: 'Deepdelve Tablets',
    galaxy: 'Deepdelve Holds', homeworld: 'Underhall of Nine Bells', stargateAddress: 'Nine Bells · Deep Spring · Flint Door',
    classification: 'Cavern-dwelling clans', factionLeader: 'Thane Orm Stonewake', flagshipClass: 'The Deepdelve Shieldhost',
    tacticalTraits: ['Stone-singers read stress in a tunnel wall', 'Clans fight fiercely in narrow halls', 'Delvers know hidden watercourses', 'A guest-mark guarantees safe passage underground'],
    loreDescription: 'The Grotto Clans dwell beneath the mountain roots. Their songs map tunnels more faithfully than ink, but outsiders must earn the right to hear them.',
    firstAppearanceEpisode: 'First entered in the Deepdelve route ledgers',
  },
  npc_genii_confederacy: {
    name: 'Ashen March Confederacy', designationOrTitle: 'The Fortified Hill Cantons', canonicalSeries: 'Cinder March Chronicles',
    galaxy: 'Cinder March', homeworld: 'Red Banner Hold', stargateAddress: 'Red Banner · Charcoal Road · Ashenford',
    classification: 'Hill-canton confederacy', factionLeader: 'Speaker-Marshal Varka Flint', flagshipClass: 'The Cinder Pikehost',
    tacticalTraits: ['Hidden stores sustain long sieges', 'Crossbow companies defend steep roads', 'Smiths repair captured engines', 'Each canton must consent before a common levy'],
    loreDescription: 'The Confederacy values preparation over spectacle. Its cantons distrust the Ashen war-crown but unite when a neighbor’s keep is threatened.',
    firstAppearanceEpisode: 'First recorded in the Cinder March truce rolls',
  },
  npc_urgo_entities: {
    name: 'Lantern Wisps', designationOrTitle: 'The Laughing Lights of the Fen', canonicalSeries: 'Lantern Cartographers’ Journals',
    galaxy: 'Whispering Fen', homeworld: 'The Blue-Lantern Pools', stargateAddress: 'Blue Pools · Reed Maze · Hush Stone',
    classification: 'Gloam-born trickster lights', factionLeader: 'The Many-Lit Moot', flagshipClass: 'The Drifting Lantern Host',
    tacticalTraits: ['False lights mislead an unwary pursuer', 'Wisps reveal hidden paths to invited guests', 'Their songs disrupt orderly marching', 'They vanish when threatened with a net'],
    loreDescription: 'The Lantern Wisps are not a crown or a people in the ordinary sense. Cartographers trade riddles with them and leave a little honey at each marked pool.',
    firstAppearanceEpisode: 'First noted in a Lantern Cartographer’s margin',
  },
  npc_humanform_replicators: {
    name: 'Oathglass Mimics', designationOrTitle: 'The Faces in the Shattered Mirror', canonicalSeries: 'Deepdelve Tablets',
    galaxy: 'Elderstone Frontier', homeworld: 'The Mirrorvault', stargateAddress: 'Mirrorvault · Glass Cairn · Hidden Face',
    classification: 'Shape-taking rune constructs', factionLeader: 'The Unnamed Reflection', flagshipClass: 'The Borrowed Banner Host',
    tacticalTraits: ['Mimics copy a witnessed formation', 'Mirror scouts infiltrate a court', 'Broken glass reveals their true form', 'They cannot repeat an oath they do not understand'],
    loreDescription: 'Oathglass Mimics were found in a sealed mirrorvault. They can borrow a face and manner but struggle to understand the loyalties they imitate.',
    firstAppearanceEpisode: 'First described in the Elderstone mirrorvault report',
  },
  npc_trust_rogue_nid: {
    name: 'Gloamveil Ciphers', designationOrTitle: 'The Quiet Hand of the March', canonicalSeries: 'Crownroad Annals',
    galaxy: 'Gloamveil Reach', homeworld: 'The Lanternless Mile', stargateAddress: 'Lanternless Mile · Black Pine · Gloam Gate',
    classification: 'Disputed intelligence houses', factionLeader: 'The Unseen Reeve', flagshipClass: 'The Moonless Riders',
    tacticalTraits: ['Ciphers seed false orders', 'Scouts discover weakly guarded roads', 'Safehouses protect messengers', 'Their loyalty is to a charter, not a crown'],
    loreDescription: 'The Ciphers trade secrets among rival courts. Some keep the roads safe; others sell a ruler the story that ruler most wants to hear.',
    firstAppearanceEpisode: 'First named in a recovered Gloamveil courier ledger',
  },
  npc_adria_ori_crusade: {
    name: 'Emberfall Votaries', designationOrTitle: 'The Crusade of the Hollow Flame', canonicalSeries: 'Cinder March Chronicles',
    galaxy: 'Emberfall Crucible', homeworld: 'The Cindered Nave', stargateAddress: 'Cindered Nave · Broken Bell · Hollow Stair',
    classification: 'Fanatical ash-crown order', factionLeader: 'Prelate Vaust of the Hollow Flame', flagshipClass: 'The Unsworn Pyrehost',
    tacticalTraits: ['Fire banners rally desperate companies', 'Votaries refuse retreat while their shrine stands', 'Ash-mages burn stores as a last defense', 'Their doctrine permits no dissent'],
    loreDescription: 'The Votaries claim the Emberfall was a divine command. Their sermons gather the dispossessed, but their flame leaves little room for a neighbor’s freedom.',
    firstAppearanceEpisode: 'First recorded after the Hollow Flame sermon at Emberfall',
  },
  npc_system_lord_council: {
    name: 'Council of Broken Banners', designationOrTitle: 'The Old Lords of the Ashen March', canonicalSeries: 'Cinder March Chronicles',
    galaxy: 'Cinder March', homeworld: 'The Sealed Oathbarrow', stargateAddress: 'Oathbarrow · Ashenford · Nine Banners',
    classification: 'Feudal war-crown council', factionLeader: 'The Nine-Banner Council', flagshipClass: 'The Gilded Siege Host',
    tacticalTraits: ['House banners summon separate levies', 'Old keeps hold deep armories', 'Rival lords sabotage one another’s supply roads', 'The Council can unite only against a greater threat'],
    loreDescription: 'The Council ruled the Ashen March through tribute and fear until the Truce of Nine Banners checked its reach. Its lords still seek to make every broken waystone a private toll.',
    firstAppearanceEpisode: 'First recorded at the signing of the Truce of Nine Banners',
  },
};

export const STARGATE_NPC_RACES: StargateNpcRace[] = PRECURSOR_CIVILIZATIONS.map((people) => ({
  ...people,
  ...ELDORIA_PEOPLE_LORE[people.id],
}));

/**
 * Converts the 18 Stargate NPC Races into playable Target Realms for Combat and Espionage
 */
export function CONVERT_NPC_RACES_TO_TARGET_REALMS(): TargetRealm[] {
  return STARGATE_NPC_RACES.map((race, index) => {
    return {
      id: `target_${race.id}`,
      commanderName: `${race.factionLeader} (${race.name})`,
      race: race.name,
      rank: race.designationOrTitle,
      score: Math.round(race.fleetStrength / 6),
      estimatedUnits: Math.round(race.fleetStrength / 450),
      estimatedNaquadah: race.resourceLoot.naquadah,
      isProtected: race.diplomaticStatus === 'Alliance Partner' || race.threatLevel === 'Harmless / Pacifist',
      defenseLevel: Math.round(race.combatStats.technologicalTier),
      antiCovertLevel: Math.max(1, Math.round(race.combatStats.sensorStealthPercent / 20)),
    };
  });
}

/**
 * Filter helpers
 */
export function getNpcRacesByGalaxy(galaxy: string): StargateNpcRace[] {
  if (galaxy === 'ALL') return STARGATE_NPC_RACES;
  return STARGATE_NPC_RACES.filter((r) => r.galaxy === galaxy);
}

export function getNpcRacesByThreat(threat: string): StargateNpcRace[] {
  if (threat === 'ALL') return STARGATE_NPC_RACES;
  return STARGATE_NPC_RACES.filter((r) => r.threatLevel === threat);
}

export function getNpcRacesBySeries(series: string): StargateNpcRace[] {
  if (series === 'ALL') return STARGATE_NPC_RACES;
  return STARGATE_NPC_RACES.filter((r) => r.canonicalSeries === series);
}
